# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_items_request_availability import ListItemsRequestAvailability
    from .list_items_request_catalog_kind import ListItemsRequestCatalogKind
    from .list_items_request_dosage_forms import ListItemsRequestDosageForms
    from .list_items_request_dosage_forms_one_item import ListItemsRequestDosageFormsOneItem
    from .list_items_request_dosage_forms_zero import ListItemsRequestDosageFormsZero
    from .list_items_request_pharmacy_ids import ListItemsRequestPharmacyIds
    from .list_items_request_requirement import ListItemsRequestRequirement
    from .list_items_request_routes import ListItemsRequestRoutes
    from .list_items_request_routes_one_item import ListItemsRequestRoutesOneItem
    from .list_items_request_routes_zero import ListItemsRequestRoutesZero
    from .list_items_request_sort import ListItemsRequestSort
    from .list_items_request_view import ListItemsRequestView
_dynamic_imports: typing.Dict[str, str] = {
    "ListItemsRequestAvailability": ".list_items_request_availability",
    "ListItemsRequestCatalogKind": ".list_items_request_catalog_kind",
    "ListItemsRequestDosageForms": ".list_items_request_dosage_forms",
    "ListItemsRequestDosageFormsOneItem": ".list_items_request_dosage_forms_one_item",
    "ListItemsRequestDosageFormsZero": ".list_items_request_dosage_forms_zero",
    "ListItemsRequestPharmacyIds": ".list_items_request_pharmacy_ids",
    "ListItemsRequestRequirement": ".list_items_request_requirement",
    "ListItemsRequestRoutes": ".list_items_request_routes",
    "ListItemsRequestRoutesOneItem": ".list_items_request_routes_one_item",
    "ListItemsRequestRoutesZero": ".list_items_request_routes_zero",
    "ListItemsRequestSort": ".list_items_request_sort",
    "ListItemsRequestView": ".list_items_request_view",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListItemsRequestAvailability",
    "ListItemsRequestCatalogKind",
    "ListItemsRequestDosageForms",
    "ListItemsRequestDosageFormsOneItem",
    "ListItemsRequestDosageFormsZero",
    "ListItemsRequestPharmacyIds",
    "ListItemsRequestRequirement",
    "ListItemsRequestRoutes",
    "ListItemsRequestRoutesOneItem",
    "ListItemsRequestRoutesZero",
    "ListItemsRequestSort",
    "ListItemsRequestView",
]
