[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[project]
name = "affinity-health-sdk"
version = "0.1.0"
description = "Python client for the Affinity API"
requires-python = ">=3.10"
dependencies = ["httpx>=0.21.2,<1", "pydantic>=1.9.2,<3", "typing-extensions>=4.0.0,<5"]
readme = "README.md"

[project.urls]
Repository = "https://github.com/affinity-health/affinity-python"

[tool.hatch.build.targets.wheel]
packages = ["src/affinity"]
