# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_catalog_items_request_availability import ListCatalogItemsRequestAvailability
    from .list_catalog_items_request_catalog_kind import ListCatalogItemsRequestCatalogKind
    from .list_catalog_items_request_dosage_forms import ListCatalogItemsRequestDosageForms
    from .list_catalog_items_request_dosage_forms_one_item import ListCatalogItemsRequestDosageFormsOneItem
    from .list_catalog_items_request_dosage_forms_zero import ListCatalogItemsRequestDosageFormsZero
    from .list_catalog_items_request_pharmacy_ids import ListCatalogItemsRequestPharmacyIds
    from .list_catalog_items_request_requirement import ListCatalogItemsRequestRequirement
    from .list_catalog_items_request_routes import ListCatalogItemsRequestRoutes
    from .list_catalog_items_request_routes_one_item import ListCatalogItemsRequestRoutesOneItem
    from .list_catalog_items_request_routes_zero import ListCatalogItemsRequestRoutesZero
    from .list_catalog_items_request_sort import ListCatalogItemsRequestSort
    from .list_catalog_items_request_view import ListCatalogItemsRequestView
    from .list_shipping_options_request_destination_type import ListShippingOptionsRequestDestinationType
_dynamic_imports: typing.Dict[str, str] = {
    "ListCatalogItemsRequestAvailability": ".list_catalog_items_request_availability",
    "ListCatalogItemsRequestCatalogKind": ".list_catalog_items_request_catalog_kind",
    "ListCatalogItemsRequestDosageForms": ".list_catalog_items_request_dosage_forms",
    "ListCatalogItemsRequestDosageFormsOneItem": ".list_catalog_items_request_dosage_forms_one_item",
    "ListCatalogItemsRequestDosageFormsZero": ".list_catalog_items_request_dosage_forms_zero",
    "ListCatalogItemsRequestPharmacyIds": ".list_catalog_items_request_pharmacy_ids",
    "ListCatalogItemsRequestRequirement": ".list_catalog_items_request_requirement",
    "ListCatalogItemsRequestRoutes": ".list_catalog_items_request_routes",
    "ListCatalogItemsRequestRoutesOneItem": ".list_catalog_items_request_routes_one_item",
    "ListCatalogItemsRequestRoutesZero": ".list_catalog_items_request_routes_zero",
    "ListCatalogItemsRequestSort": ".list_catalog_items_request_sort",
    "ListCatalogItemsRequestView": ".list_catalog_items_request_view",
    "ListShippingOptionsRequestDestinationType": ".list_shipping_options_request_destination_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListCatalogItemsRequestAvailability",
    "ListCatalogItemsRequestCatalogKind",
    "ListCatalogItemsRequestDosageForms",
    "ListCatalogItemsRequestDosageFormsOneItem",
    "ListCatalogItemsRequestDosageFormsZero",
    "ListCatalogItemsRequestPharmacyIds",
    "ListCatalogItemsRequestRequirement",
    "ListCatalogItemsRequestRoutes",
    "ListCatalogItemsRequestRoutesOneItem",
    "ListCatalogItemsRequestRoutesZero",
    "ListCatalogItemsRequestSort",
    "ListCatalogItemsRequestView",
    "ListShippingOptionsRequestDestinationType",
]
