# This file was auto-generated by Fern from our API Definition.

import typing

from .list_catalog_items_request_routes_one_item import ListCatalogItemsRequestRoutesOneItem
from .list_catalog_items_request_routes_zero import ListCatalogItemsRequestRoutesZero

ListCatalogItemsRequestRoutes = typing.Union[
    ListCatalogItemsRequestRoutesZero, typing.List[ListCatalogItemsRequestRoutesOneItem]
]
