# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_patient_response import CreatePatientResponse
from ..types.delete_patient_response import DeletePatientResponse
from ..types.get_patient_response import GetPatientResponse
from ..types.list_patients_response import ListPatientsResponse
from ..types.update_patient_response import UpdatePatientResponse
from .raw_client import AsyncRawPatientsClient, RawPatientsClient
from .types.create_patient_request_address import CreatePatientRequestAddress
from .types.create_patient_request_addresses_item import CreatePatientRequestAddressesItem
from .types.create_patient_request_clinical_profile import CreatePatientRequestClinicalProfile
from .types.create_patient_request_encounters_item import CreatePatientRequestEncountersItem
from .types.create_patient_request_external_identities_item import CreatePatientRequestExternalIdentitiesItem
from .types.create_patient_request_gender import CreatePatientRequestGender
from .types.create_patient_request_measurements_item import CreatePatientRequestMeasurementsItem
from .types.create_patient_request_name import CreatePatientRequestName
from .types.create_patient_request_programs_item import CreatePatientRequestProgramsItem
from .types.list_patients_request_gender import ListPatientsRequestGender
from .types.list_patients_request_sort import ListPatientsRequestSort
from .types.list_patients_request_status import ListPatientsRequestStatus
from .types.update_patient_request_address import UpdatePatientRequestAddress
from .types.update_patient_request_addresses_item import UpdatePatientRequestAddressesItem
from .types.update_patient_request_clinical_profile import UpdatePatientRequestClinicalProfile
from .types.update_patient_request_encounters_item import UpdatePatientRequestEncountersItem
from .types.update_patient_request_external_identities_item import UpdatePatientRequestExternalIdentitiesItem
from .types.update_patient_request_gender import UpdatePatientRequestGender
from .types.update_patient_request_measurements_item import UpdatePatientRequestMeasurementsItem
from .types.update_patient_request_name import UpdatePatientRequestName
from .types.update_patient_request_programs_item import UpdatePatientRequestProgramsItem
from .types.update_patient_request_status import UpdatePatientRequestStatus

if typing.TYPE_CHECKING:
    from .addresses.client import AddressesClient, AsyncAddressesClient
    from .allergies.client import AllergiesClient, AsyncAllergiesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PatientsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPatientsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._addresses: typing.Optional[AddressesClient] = None
        self._allergies: typing.Optional[AllergiesClient] = None

    @property
    def with_raw_response(self) -> RawPatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPatientsClient
        """
        return self._raw_client

    def list(
        self,
        practice_id: str,
        *,
        ending_before: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        external_identity_source: typing.Optional[str] = None,
        external_identity_value: typing.Optional[str] = None,
        gender: typing.Optional[ListPatientsRequestGender] = None,
        last_order_after: typing.Optional[str] = None,
        last_order_before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        program: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        sort: typing.Optional[ListPatientsRequestSort] = None,
        starting_after: typing.Optional[str] = None,
        states: typing.Optional[str] = None,
        status: typing.Optional[ListPatientsRequestStatus] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPatientsResponse:
        """
        Lists patients in one practice and mode. Use externalId for an exact match in the calling integration's namespace. Use externalIdentitySource with externalIdentityValue to search an explicit alias. Identity matching is case-sensitive after trimming whitespace. Other filters also apply.

        Parameters
        ----------
        practice_id : str

        ending_before : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identity_source : typing.Optional[str]

        external_identity_value : typing.Optional[str]

        gender : typing.Optional[ListPatientsRequestGender]

        last_order_after : typing.Optional[str]

        last_order_before : typing.Optional[str]

        limit : typing.Optional[int]

        program : typing.Optional[str]

        query : typing.Optional[str]

        sort : typing.Optional[ListPatientsRequestSort]

        starting_after : typing.Optional[str]

        states : typing.Optional[str]

        status : typing.Optional[ListPatientsRequestStatus]

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPatientsResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.patients.list(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            ending_before="pat_01j2y8m6jcc9tt24af5pw9x1bc",
            starting_after="pat_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.list(
            practice_id,
            ending_before=ending_before,
            external_id=external_id,
            external_identity_source=external_identity_source,
            external_identity_value=external_identity_value,
            gender=gender,
            last_order_after=last_order_after,
            last_order_before=last_order_before,
            limit=limit,
            program=program,
            query=query,
            sort=sort,
            starting_after=starting_after,
            states=states,
            status=status,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        practice_id: str,
        *,
        date_of_birth: str,
        name: CreatePatientRequestName,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        address: typing.Optional[CreatePatientRequestAddress] = OMIT,
        clinical_profile: typing.Optional[CreatePatientRequestClinicalProfile] = OMIT,
        email: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        external_identities: typing.Optional[typing.Sequence[CreatePatientRequestExternalIdentitiesItem]] = OMIT,
        addresses: typing.Optional[typing.Sequence[CreatePatientRequestAddressesItem]] = OMIT,
        encounters: typing.Optional[typing.Sequence[CreatePatientRequestEncountersItem]] = OMIT,
        gender: typing.Optional[CreatePatientRequestGender] = OMIT,
        location_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        medical_record_number: typing.Optional[str] = OMIT,
        measurements: typing.Optional[typing.Sequence[CreatePatientRequestMeasurementsItem]] = OMIT,
        phone: typing.Optional[str] = OMIT,
        programs: typing.Optional[typing.Sequence[CreatePatientRequestProgramsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePatientResponse:
        """
        Creates a patient or resolves a matching externalId or external identity within this practice and mode. externalId belongs to the calling integration; externalIdentities holds aliases from other systems. Resolution preserves existing demographics; use PATCH to update them. Conflicting identifiers return 409. Email never merges patients. API keys require Idempotency-Key.

        Parameters
        ----------
        practice_id : str

        date_of_birth : str

        name : CreatePatientRequestName

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        address : typing.Optional[CreatePatientRequestAddress]

        clinical_profile : typing.Optional[CreatePatientRequestClinicalProfile]

        email : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identities : typing.Optional[typing.Sequence[CreatePatientRequestExternalIdentitiesItem]]

        addresses : typing.Optional[typing.Sequence[CreatePatientRequestAddressesItem]]

        encounters : typing.Optional[typing.Sequence[CreatePatientRequestEncountersItem]]

        gender : typing.Optional[CreatePatientRequestGender]

        location_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        medical_record_number : typing.Optional[str]

        measurements : typing.Optional[typing.Sequence[CreatePatientRequestMeasurementsItem]]

        phone : typing.Optional[str]

        programs : typing.Optional[typing.Sequence[CreatePatientRequestProgramsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePatientResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity
        from affinity.patients import CreatePatientRequestName

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.patients.create(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            date_of_birth="dateOfBirth",
            name=CreatePatientRequestName(
                first="first",
                last="last",
            ),
        )
        """
        _response = self._raw_client.create(
            practice_id,
            date_of_birth=date_of_birth,
            name=name,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            address=address,
            clinical_profile=clinical_profile,
            email=email,
            external_id=external_id,
            external_identities=external_identities,
            addresses=addresses,
            encounters=encounters,
            gender=gender,
            location_id=location_id,
            metadata=metadata,
            medical_record_number=medical_record_number,
            measurements=measurements,
            phone=phone,
            programs=programs,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        practice_id: str,
        patient_id: str,
        *,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPatientResponse:
        """
        Returns one patient in the authorized practice and mode.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPatientResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.patients.get(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get(
            practice_id,
            patient_id,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        practice_id: str,
        patient_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePatientResponse:
        """
        Requires patients:write and Idempotency-Key for API keys. Permanently deletes a patient with no order history. Any order history returns 409; use Update patient with status archived instead. Available to practice keys and authorized platform keys. Reusing the same idempotency key returns the original deletion result.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePatientResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.patients.delete(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.delete(
            practice_id,
            patient_id,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    def update(
        self,
        practice_id: str,
        patient_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        address: typing.Optional[UpdatePatientRequestAddress] = OMIT,
        clinical_profile: typing.Optional[UpdatePatientRequestClinicalProfile] = OMIT,
        date_of_birth: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        external_identities: typing.Optional[typing.Sequence[UpdatePatientRequestExternalIdentitiesItem]] = OMIT,
        addresses: typing.Optional[typing.Sequence[UpdatePatientRequestAddressesItem]] = OMIT,
        encounters: typing.Optional[typing.Sequence[UpdatePatientRequestEncountersItem]] = OMIT,
        gender: typing.Optional[UpdatePatientRequestGender] = OMIT,
        location_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        medical_record_number: typing.Optional[str] = OMIT,
        measurements: typing.Optional[typing.Sequence[UpdatePatientRequestMeasurementsItem]] = OMIT,
        name: typing.Optional[UpdatePatientRequestName] = OMIT,
        programs: typing.Optional[typing.Sequence[UpdatePatientRequestProgramsItem]] = OMIT,
        phone: typing.Optional[str] = OMIT,
        status: typing.Optional[UpdatePatientRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePatientResponse:
        """
        Updates a patient in the current practice and mode. Omitted fields remain unchanged; null clears an optional field. externalId updates the calling integration's identifier. externalIdentities replaces its explicit aliases. Identifiers cannot be reassigned from another patient. API keys require Idempotency-Key.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        address : typing.Optional[UpdatePatientRequestAddress]

        clinical_profile : typing.Optional[UpdatePatientRequestClinicalProfile]

        date_of_birth : typing.Optional[str]

        email : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identities : typing.Optional[typing.Sequence[UpdatePatientRequestExternalIdentitiesItem]]

        addresses : typing.Optional[typing.Sequence[UpdatePatientRequestAddressesItem]]

        encounters : typing.Optional[typing.Sequence[UpdatePatientRequestEncountersItem]]

        gender : typing.Optional[UpdatePatientRequestGender]

        location_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        medical_record_number : typing.Optional[str]

        measurements : typing.Optional[typing.Sequence[UpdatePatientRequestMeasurementsItem]]

        name : typing.Optional[UpdatePatientRequestName]

        programs : typing.Optional[typing.Sequence[UpdatePatientRequestProgramsItem]]

        phone : typing.Optional[str]

        status : typing.Optional[UpdatePatientRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePatientResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.patients.update(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.update(
            practice_id,
            patient_id,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            address=address,
            clinical_profile=clinical_profile,
            date_of_birth=date_of_birth,
            email=email,
            external_id=external_id,
            external_identities=external_identities,
            addresses=addresses,
            encounters=encounters,
            gender=gender,
            location_id=location_id,
            metadata=metadata,
            medical_record_number=medical_record_number,
            measurements=measurements,
            name=name,
            programs=programs,
            phone=phone,
            status=status,
            request_options=request_options,
        )
        return _response.data

    @property
    def addresses(self):
        if self._addresses is None:
            from .addresses.client import AddressesClient  # noqa: E402

            self._addresses = AddressesClient(client_wrapper=self._client_wrapper)
        return self._addresses

    @property
    def allergies(self):
        if self._allergies is None:
            from .allergies.client import AllergiesClient  # noqa: E402

            self._allergies = AllergiesClient(client_wrapper=self._client_wrapper)
        return self._allergies


class AsyncPatientsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPatientsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._addresses: typing.Optional[AsyncAddressesClient] = None
        self._allergies: typing.Optional[AsyncAllergiesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawPatientsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPatientsClient
        """
        return self._raw_client

    async def list(
        self,
        practice_id: str,
        *,
        ending_before: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        external_identity_source: typing.Optional[str] = None,
        external_identity_value: typing.Optional[str] = None,
        gender: typing.Optional[ListPatientsRequestGender] = None,
        last_order_after: typing.Optional[str] = None,
        last_order_before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        program: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        sort: typing.Optional[ListPatientsRequestSort] = None,
        starting_after: typing.Optional[str] = None,
        states: typing.Optional[str] = None,
        status: typing.Optional[ListPatientsRequestStatus] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPatientsResponse:
        """
        Lists patients in one practice and mode. Use externalId for an exact match in the calling integration's namespace. Use externalIdentitySource with externalIdentityValue to search an explicit alias. Identity matching is case-sensitive after trimming whitespace. Other filters also apply.

        Parameters
        ----------
        practice_id : str

        ending_before : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identity_source : typing.Optional[str]

        external_identity_value : typing.Optional[str]

        gender : typing.Optional[ListPatientsRequestGender]

        last_order_after : typing.Optional[str]

        last_order_before : typing.Optional[str]

        limit : typing.Optional[int]

        program : typing.Optional[str]

        query : typing.Optional[str]

        sort : typing.Optional[ListPatientsRequestSort]

        starting_after : typing.Optional[str]

        states : typing.Optional[str]

        status : typing.Optional[ListPatientsRequestStatus]

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPatientsResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.list(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                ending_before="pat_01j2y8m6jcc9tt24af5pw9x1bc",
                starting_after="pat_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            practice_id,
            ending_before=ending_before,
            external_id=external_id,
            external_identity_source=external_identity_source,
            external_identity_value=external_identity_value,
            gender=gender,
            last_order_after=last_order_after,
            last_order_before=last_order_before,
            limit=limit,
            program=program,
            query=query,
            sort=sort,
            starting_after=starting_after,
            states=states,
            status=status,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        practice_id: str,
        *,
        date_of_birth: str,
        name: CreatePatientRequestName,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        address: typing.Optional[CreatePatientRequestAddress] = OMIT,
        clinical_profile: typing.Optional[CreatePatientRequestClinicalProfile] = OMIT,
        email: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        external_identities: typing.Optional[typing.Sequence[CreatePatientRequestExternalIdentitiesItem]] = OMIT,
        addresses: typing.Optional[typing.Sequence[CreatePatientRequestAddressesItem]] = OMIT,
        encounters: typing.Optional[typing.Sequence[CreatePatientRequestEncountersItem]] = OMIT,
        gender: typing.Optional[CreatePatientRequestGender] = OMIT,
        location_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        medical_record_number: typing.Optional[str] = OMIT,
        measurements: typing.Optional[typing.Sequence[CreatePatientRequestMeasurementsItem]] = OMIT,
        phone: typing.Optional[str] = OMIT,
        programs: typing.Optional[typing.Sequence[CreatePatientRequestProgramsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePatientResponse:
        """
        Creates a patient or resolves a matching externalId or external identity within this practice and mode. externalId belongs to the calling integration; externalIdentities holds aliases from other systems. Resolution preserves existing demographics; use PATCH to update them. Conflicting identifiers return 409. Email never merges patients. API keys require Idempotency-Key.

        Parameters
        ----------
        practice_id : str

        date_of_birth : str

        name : CreatePatientRequestName

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        address : typing.Optional[CreatePatientRequestAddress]

        clinical_profile : typing.Optional[CreatePatientRequestClinicalProfile]

        email : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identities : typing.Optional[typing.Sequence[CreatePatientRequestExternalIdentitiesItem]]

        addresses : typing.Optional[typing.Sequence[CreatePatientRequestAddressesItem]]

        encounters : typing.Optional[typing.Sequence[CreatePatientRequestEncountersItem]]

        gender : typing.Optional[CreatePatientRequestGender]

        location_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        medical_record_number : typing.Optional[str]

        measurements : typing.Optional[typing.Sequence[CreatePatientRequestMeasurementsItem]]

        phone : typing.Optional[str]

        programs : typing.Optional[typing.Sequence[CreatePatientRequestProgramsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePatientResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity
        from affinity.patients import CreatePatientRequestName

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.create(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                date_of_birth="dateOfBirth",
                name=CreatePatientRequestName(
                    first="first",
                    last="last",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            practice_id,
            date_of_birth=date_of_birth,
            name=name,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            address=address,
            clinical_profile=clinical_profile,
            email=email,
            external_id=external_id,
            external_identities=external_identities,
            addresses=addresses,
            encounters=encounters,
            gender=gender,
            location_id=location_id,
            metadata=metadata,
            medical_record_number=medical_record_number,
            measurements=measurements,
            phone=phone,
            programs=programs,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        practice_id: str,
        patient_id: str,
        *,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPatientResponse:
        """
        Returns one patient in the authorized practice and mode.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPatientResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.get(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            practice_id,
            patient_id,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        practice_id: str,
        patient_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePatientResponse:
        """
        Requires patients:write and Idempotency-Key for API keys. Permanently deletes a patient with no order history. Any order history returns 409; use Update patient with status archived instead. Available to practice keys and authorized platform keys. Reusing the same idempotency key returns the original deletion result.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePatientResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.delete(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            practice_id,
            patient_id,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            request_options=request_options,
        )
        return _response.data

    async def update(
        self,
        practice_id: str,
        patient_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        affinity_actor_id: typing.Optional[str] = None,
        affinity_actor_type: typing.Optional[str] = None,
        address: typing.Optional[UpdatePatientRequestAddress] = OMIT,
        clinical_profile: typing.Optional[UpdatePatientRequestClinicalProfile] = OMIT,
        date_of_birth: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        external_identities: typing.Optional[typing.Sequence[UpdatePatientRequestExternalIdentitiesItem]] = OMIT,
        addresses: typing.Optional[typing.Sequence[UpdatePatientRequestAddressesItem]] = OMIT,
        encounters: typing.Optional[typing.Sequence[UpdatePatientRequestEncountersItem]] = OMIT,
        gender: typing.Optional[UpdatePatientRequestGender] = OMIT,
        location_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        medical_record_number: typing.Optional[str] = OMIT,
        measurements: typing.Optional[typing.Sequence[UpdatePatientRequestMeasurementsItem]] = OMIT,
        name: typing.Optional[UpdatePatientRequestName] = OMIT,
        programs: typing.Optional[typing.Sequence[UpdatePatientRequestProgramsItem]] = OMIT,
        phone: typing.Optional[str] = OMIT,
        status: typing.Optional[UpdatePatientRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePatientResponse:
        """
        Updates a patient in the current practice and mode. Omitted fields remain unchanged; null clears an optional field. externalId updates the calling integration's identifier. externalIdentities replaces its explicit aliases. Identifiers cannot be reassigned from another patient. API keys require Idempotency-Key.

        Parameters
        ----------
        practice_id : str

        patient_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        affinity_actor_id : typing.Optional[str]
            Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.

        affinity_actor_type : typing.Optional[str]
            Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.

        address : typing.Optional[UpdatePatientRequestAddress]

        clinical_profile : typing.Optional[UpdatePatientRequestClinicalProfile]

        date_of_birth : typing.Optional[str]

        email : typing.Optional[str]

        external_id : typing.Optional[str]

        external_identities : typing.Optional[typing.Sequence[UpdatePatientRequestExternalIdentitiesItem]]

        addresses : typing.Optional[typing.Sequence[UpdatePatientRequestAddressesItem]]

        encounters : typing.Optional[typing.Sequence[UpdatePatientRequestEncountersItem]]

        gender : typing.Optional[UpdatePatientRequestGender]

        location_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        medical_record_number : typing.Optional[str]

        measurements : typing.Optional[typing.Sequence[UpdatePatientRequestMeasurementsItem]]

        name : typing.Optional[UpdatePatientRequestName]

        programs : typing.Optional[typing.Sequence[UpdatePatientRequestProgramsItem]]

        phone : typing.Optional[str]

        status : typing.Optional[UpdatePatientRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePatientResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patients.update(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                patient_id="pat_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            practice_id,
            patient_id,
            idempotency_key=idempotency_key,
            affinity_actor_id=affinity_actor_id,
            affinity_actor_type=affinity_actor_type,
            address=address,
            clinical_profile=clinical_profile,
            date_of_birth=date_of_birth,
            email=email,
            external_id=external_id,
            external_identities=external_identities,
            addresses=addresses,
            encounters=encounters,
            gender=gender,
            location_id=location_id,
            metadata=metadata,
            medical_record_number=medical_record_number,
            measurements=measurements,
            name=name,
            programs=programs,
            phone=phone,
            status=status,
            request_options=request_options,
        )
        return _response.data

    @property
    def addresses(self):
        if self._addresses is None:
            from .addresses.client import AsyncAddressesClient  # noqa: E402

            self._addresses = AsyncAddressesClient(client_wrapper=self._client_wrapper)
        return self._addresses

    @property
    def allergies(self):
        if self._allergies is None:
            from .allergies.client import AsyncAllergiesClient  # noqa: E402

            self._allergies = AsyncAllergiesClient(client_wrapper=self._client_wrapper)
        return self._allergies
