# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_order_request_metadata_value import CreateOrderRequestMetadataValue
    from .create_order_request_otc_items_item import CreateOrderRequestOtcItemsItem
    from .create_order_request_patient import CreateOrderRequestPatient
    from .create_order_request_patient_address import CreateOrderRequestPatientAddress
    from .create_order_request_patient_address_country import CreateOrderRequestPatientAddressCountry
    from .create_order_request_patient_addresses_item import CreateOrderRequestPatientAddressesItem
    from .create_order_request_patient_addresses_item_address import CreateOrderRequestPatientAddressesItemAddress
    from .create_order_request_patient_addresses_item_address_country import (
        CreateOrderRequestPatientAddressesItemAddressCountry,
    )
    from .create_order_request_patient_clinical_profile import CreateOrderRequestPatientClinicalProfile
    from .create_order_request_patient_clinical_profile_height_inches import (
        CreateOrderRequestPatientClinicalProfileHeightInches,
    )
    from .create_order_request_patient_clinical_profile_height_inches_one import (
        CreateOrderRequestPatientClinicalProfileHeightInchesOne,
    )
    from .create_order_request_patient_clinical_profile_weight_pounds import (
        CreateOrderRequestPatientClinicalProfileWeightPounds,
    )
    from .create_order_request_patient_clinical_profile_weight_pounds_one import (
        CreateOrderRequestPatientClinicalProfileWeightPoundsOne,
    )
    from .create_order_request_patient_encounters_item import CreateOrderRequestPatientEncountersItem
    from .create_order_request_patient_external_identities_item import CreateOrderRequestPatientExternalIdentitiesItem
    from .create_order_request_patient_gender import CreateOrderRequestPatientGender
    from .create_order_request_patient_measurements_item import CreateOrderRequestPatientMeasurementsItem
    from .create_order_request_patient_measurements_item_height_centimeters import (
        CreateOrderRequestPatientMeasurementsItemHeightCentimeters,
    )
    from .create_order_request_patient_measurements_item_height_centimeters_one import (
        CreateOrderRequestPatientMeasurementsItemHeightCentimetersOne,
    )
    from .create_order_request_patient_measurements_item_weight_kilograms import (
        CreateOrderRequestPatientMeasurementsItemWeightKilograms,
    )
    from .create_order_request_patient_measurements_item_weight_kilograms_one import (
        CreateOrderRequestPatientMeasurementsItemWeightKilogramsOne,
    )
    from .create_order_request_patient_name import CreateOrderRequestPatientName
    from .create_order_request_patient_programs_item import CreateOrderRequestPatientProgramsItem
    from .create_order_request_patient_programs_item_status import CreateOrderRequestPatientProgramsItemStatus
    from .create_order_request_prescriber import CreateOrderRequestPrescriber
    from .create_order_request_prescriber_profile import CreateOrderRequestPrescriberProfile
    from .create_order_request_prescriptions_item import CreateOrderRequestPrescriptionsItem
    from .create_order_request_prescriptions_item_clinical import CreateOrderRequestPrescriptionsItemClinical
    from .create_order_request_prescriptions_item_clinical_compounding_reason import (
        CreateOrderRequestPrescriptionsItemClinicalCompoundingReason,
    )
    from .create_order_request_prescriptions_item_clinical_compounding_reason_category import (
        CreateOrderRequestPrescriptionsItemClinicalCompoundingReasonCategory,
    )
    from .create_order_request_prescriptions_item_clinical_diagnoses_item import (
        CreateOrderRequestPrescriptionsItemClinicalDiagnosesItem,
    )
    from .create_order_request_prescriptions_item_clinical_diagnosis_review_status import (
        CreateOrderRequestPrescriptionsItemClinicalDiagnosisReviewStatus,
    )
    from .create_order_request_prescriptions_item_clinical_medication_review_status import (
        CreateOrderRequestPrescriptionsItemClinicalMedicationReviewStatus,
    )
    from .create_order_request_prescriptions_item_clinical_observations_item import (
        CreateOrderRequestPrescriptionsItemClinicalObservationsItem,
    )
    from .create_order_request_prescriptions_item_clinical_observations_item_value import (
        CreateOrderRequestPrescriptionsItemClinicalObservationsItemValue,
    )
    from .create_order_request_prescriptions_item_clinical_observations_item_value_one import (
        CreateOrderRequestPrescriptionsItemClinicalObservationsItemValueOne,
    )
    from .create_order_request_prescriptions_item_dispensing import CreateOrderRequestPrescriptionsItemDispensing
    from .create_order_request_prescriptions_item_dispensing_shipping_destination_type import (
        CreateOrderRequestPrescriptionsItemDispensingShippingDestinationType,
    )
    from .create_order_request_prescriptions_item_quantity import CreateOrderRequestPrescriptionsItemQuantity
    from .create_order_request_prescriptions_item_quantity_one import CreateOrderRequestPrescriptionsItemQuantityOne
    from .create_order_request_prescriptions_item_structured_sig import CreateOrderRequestPrescriptionsItemStructuredSig
    from .list_orders_request_sort import ListOrdersRequestSort
    from .list_orders_request_status import ListOrdersRequestStatus
    from .preview_order_request_otc_items_item import PreviewOrderRequestOtcItemsItem
    from .preview_order_request_patient import PreviewOrderRequestPatient
    from .preview_order_request_patient_address import PreviewOrderRequestPatientAddress
    from .preview_order_request_patient_address_country import PreviewOrderRequestPatientAddressCountry
    from .preview_order_request_patient_addresses_item import PreviewOrderRequestPatientAddressesItem
    from .preview_order_request_patient_addresses_item_address import PreviewOrderRequestPatientAddressesItemAddress
    from .preview_order_request_patient_addresses_item_address_country import (
        PreviewOrderRequestPatientAddressesItemAddressCountry,
    )
    from .preview_order_request_patient_clinical_profile import PreviewOrderRequestPatientClinicalProfile
    from .preview_order_request_patient_clinical_profile_height_inches import (
        PreviewOrderRequestPatientClinicalProfileHeightInches,
    )
    from .preview_order_request_patient_clinical_profile_height_inches_one import (
        PreviewOrderRequestPatientClinicalProfileHeightInchesOne,
    )
    from .preview_order_request_patient_clinical_profile_weight_pounds import (
        PreviewOrderRequestPatientClinicalProfileWeightPounds,
    )
    from .preview_order_request_patient_clinical_profile_weight_pounds_one import (
        PreviewOrderRequestPatientClinicalProfileWeightPoundsOne,
    )
    from .preview_order_request_patient_encounters_item import PreviewOrderRequestPatientEncountersItem
    from .preview_order_request_patient_external_identities_item import PreviewOrderRequestPatientExternalIdentitiesItem
    from .preview_order_request_patient_gender import PreviewOrderRequestPatientGender
    from .preview_order_request_patient_measurements_item import PreviewOrderRequestPatientMeasurementsItem
    from .preview_order_request_patient_measurements_item_height_centimeters import (
        PreviewOrderRequestPatientMeasurementsItemHeightCentimeters,
    )
    from .preview_order_request_patient_measurements_item_height_centimeters_one import (
        PreviewOrderRequestPatientMeasurementsItemHeightCentimetersOne,
    )
    from .preview_order_request_patient_measurements_item_weight_kilograms import (
        PreviewOrderRequestPatientMeasurementsItemWeightKilograms,
    )
    from .preview_order_request_patient_measurements_item_weight_kilograms_one import (
        PreviewOrderRequestPatientMeasurementsItemWeightKilogramsOne,
    )
    from .preview_order_request_patient_name import PreviewOrderRequestPatientName
    from .preview_order_request_patient_programs_item import PreviewOrderRequestPatientProgramsItem
    from .preview_order_request_patient_programs_item_status import PreviewOrderRequestPatientProgramsItemStatus
    from .preview_order_request_prescriber import PreviewOrderRequestPrescriber
    from .preview_order_request_prescriber_profile import PreviewOrderRequestPrescriberProfile
    from .preview_order_request_prescriptions_item import PreviewOrderRequestPrescriptionsItem
    from .preview_order_request_prescriptions_item_overrides import PreviewOrderRequestPrescriptionsItemOverrides
    from .preview_order_request_prescriptions_item_overrides_clinical import (
        PreviewOrderRequestPrescriptionsItemOverridesClinical,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_compounding_reason import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_compounding_reason_category import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReasonCategory,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_diagnoses_item import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_diagnosis_review_status import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_medication_review_status import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_observations_item import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_observations_item_value import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValue,
    )
    from .preview_order_request_prescriptions_item_overrides_clinical_observations_item_value_one import (
        PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValueOne,
    )
    from .preview_order_request_prescriptions_item_overrides_dispensing import (
        PreviewOrderRequestPrescriptionsItemOverridesDispensing,
    )
    from .preview_order_request_prescriptions_item_overrides_dispensing_shipping_destination_type import (
        PreviewOrderRequestPrescriptionsItemOverridesDispensingShippingDestinationType,
    )
    from .preview_order_request_prescriptions_item_overrides_quantity import (
        PreviewOrderRequestPrescriptionsItemOverridesQuantity,
    )
    from .preview_order_request_prescriptions_item_overrides_sig import (
        PreviewOrderRequestPrescriptionsItemOverridesSig,
        PreviewOrderRequestPrescriptionsItemOverridesSig_FreeText,
        PreviewOrderRequestPrescriptionsItemOverridesSig_Structured,
        PreviewOrderRequestPrescriptionsItemOverridesSig_Template,
    )
    from .preview_order_request_prescriptions_item_overrides_sig_free_text import (
        PreviewOrderRequestPrescriptionsItemOverridesSigFreeText,
    )
    from .preview_order_request_prescriptions_item_overrides_sig_structured import (
        PreviewOrderRequestPrescriptionsItemOverridesSigStructured,
    )
    from .preview_order_request_prescriptions_item_overrides_sig_structured_fields import (
        PreviewOrderRequestPrescriptionsItemOverridesSigStructuredFields,
    )
    from .preview_order_request_prescriptions_item_overrides_sig_template import (
        PreviewOrderRequestPrescriptionsItemOverridesSigTemplate,
    )
    from .preview_order_request_shipping import PreviewOrderRequestShipping
    from .preview_order_request_shipping_selection import PreviewOrderRequestShippingSelection
    from .reject_order_request_expected_versions_item import RejectOrderRequestExpectedVersionsItem
    from .reject_order_request_prescriber import RejectOrderRequestPrescriber
    from .reject_order_request_prescriber_profile import RejectOrderRequestPrescriberProfile
    from .sign_and_submit_order_request_expected_versions_item import SignAndSubmitOrderRequestExpectedVersionsItem
    from .sign_and_submit_order_request_prescriber import SignAndSubmitOrderRequestPrescriber
    from .sign_and_submit_order_request_prescriber_profile import SignAndSubmitOrderRequestPrescriberProfile
    from .sign_order_request_expected_versions_item import SignOrderRequestExpectedVersionsItem
    from .sign_order_request_prescriber import SignOrderRequestPrescriber
    from .sign_order_request_prescriber_profile import SignOrderRequestPrescriberProfile
    from .submit_order_request_prescriber import SubmitOrderRequestPrescriber
    from .submit_order_request_prescriber_profile import SubmitOrderRequestPrescriberProfile
_dynamic_imports: typing.Dict[str, str] = {
    "CreateOrderRequestMetadataValue": ".create_order_request_metadata_value",
    "CreateOrderRequestOtcItemsItem": ".create_order_request_otc_items_item",
    "CreateOrderRequestPatient": ".create_order_request_patient",
    "CreateOrderRequestPatientAddress": ".create_order_request_patient_address",
    "CreateOrderRequestPatientAddressCountry": ".create_order_request_patient_address_country",
    "CreateOrderRequestPatientAddressesItem": ".create_order_request_patient_addresses_item",
    "CreateOrderRequestPatientAddressesItemAddress": ".create_order_request_patient_addresses_item_address",
    "CreateOrderRequestPatientAddressesItemAddressCountry": ".create_order_request_patient_addresses_item_address_country",
    "CreateOrderRequestPatientClinicalProfile": ".create_order_request_patient_clinical_profile",
    "CreateOrderRequestPatientClinicalProfileHeightInches": ".create_order_request_patient_clinical_profile_height_inches",
    "CreateOrderRequestPatientClinicalProfileHeightInchesOne": ".create_order_request_patient_clinical_profile_height_inches_one",
    "CreateOrderRequestPatientClinicalProfileWeightPounds": ".create_order_request_patient_clinical_profile_weight_pounds",
    "CreateOrderRequestPatientClinicalProfileWeightPoundsOne": ".create_order_request_patient_clinical_profile_weight_pounds_one",
    "CreateOrderRequestPatientEncountersItem": ".create_order_request_patient_encounters_item",
    "CreateOrderRequestPatientExternalIdentitiesItem": ".create_order_request_patient_external_identities_item",
    "CreateOrderRequestPatientGender": ".create_order_request_patient_gender",
    "CreateOrderRequestPatientMeasurementsItem": ".create_order_request_patient_measurements_item",
    "CreateOrderRequestPatientMeasurementsItemHeightCentimeters": ".create_order_request_patient_measurements_item_height_centimeters",
    "CreateOrderRequestPatientMeasurementsItemHeightCentimetersOne": ".create_order_request_patient_measurements_item_height_centimeters_one",
    "CreateOrderRequestPatientMeasurementsItemWeightKilograms": ".create_order_request_patient_measurements_item_weight_kilograms",
    "CreateOrderRequestPatientMeasurementsItemWeightKilogramsOne": ".create_order_request_patient_measurements_item_weight_kilograms_one",
    "CreateOrderRequestPatientName": ".create_order_request_patient_name",
    "CreateOrderRequestPatientProgramsItem": ".create_order_request_patient_programs_item",
    "CreateOrderRequestPatientProgramsItemStatus": ".create_order_request_patient_programs_item_status",
    "CreateOrderRequestPrescriber": ".create_order_request_prescriber",
    "CreateOrderRequestPrescriberProfile": ".create_order_request_prescriber_profile",
    "CreateOrderRequestPrescriptionsItem": ".create_order_request_prescriptions_item",
    "CreateOrderRequestPrescriptionsItemClinical": ".create_order_request_prescriptions_item_clinical",
    "CreateOrderRequestPrescriptionsItemClinicalCompoundingReason": ".create_order_request_prescriptions_item_clinical_compounding_reason",
    "CreateOrderRequestPrescriptionsItemClinicalCompoundingReasonCategory": ".create_order_request_prescriptions_item_clinical_compounding_reason_category",
    "CreateOrderRequestPrescriptionsItemClinicalDiagnosesItem": ".create_order_request_prescriptions_item_clinical_diagnoses_item",
    "CreateOrderRequestPrescriptionsItemClinicalDiagnosisReviewStatus": ".create_order_request_prescriptions_item_clinical_diagnosis_review_status",
    "CreateOrderRequestPrescriptionsItemClinicalMedicationReviewStatus": ".create_order_request_prescriptions_item_clinical_medication_review_status",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItem": ".create_order_request_prescriptions_item_clinical_observations_item",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItemValue": ".create_order_request_prescriptions_item_clinical_observations_item_value",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItemValueOne": ".create_order_request_prescriptions_item_clinical_observations_item_value_one",
    "CreateOrderRequestPrescriptionsItemDispensing": ".create_order_request_prescriptions_item_dispensing",
    "CreateOrderRequestPrescriptionsItemDispensingShippingDestinationType": ".create_order_request_prescriptions_item_dispensing_shipping_destination_type",
    "CreateOrderRequestPrescriptionsItemQuantity": ".create_order_request_prescriptions_item_quantity",
    "CreateOrderRequestPrescriptionsItemQuantityOne": ".create_order_request_prescriptions_item_quantity_one",
    "CreateOrderRequestPrescriptionsItemStructuredSig": ".create_order_request_prescriptions_item_structured_sig",
    "ListOrdersRequestSort": ".list_orders_request_sort",
    "ListOrdersRequestStatus": ".list_orders_request_status",
    "PreviewOrderRequestOtcItemsItem": ".preview_order_request_otc_items_item",
    "PreviewOrderRequestPatient": ".preview_order_request_patient",
    "PreviewOrderRequestPatientAddress": ".preview_order_request_patient_address",
    "PreviewOrderRequestPatientAddressCountry": ".preview_order_request_patient_address_country",
    "PreviewOrderRequestPatientAddressesItem": ".preview_order_request_patient_addresses_item",
    "PreviewOrderRequestPatientAddressesItemAddress": ".preview_order_request_patient_addresses_item_address",
    "PreviewOrderRequestPatientAddressesItemAddressCountry": ".preview_order_request_patient_addresses_item_address_country",
    "PreviewOrderRequestPatientClinicalProfile": ".preview_order_request_patient_clinical_profile",
    "PreviewOrderRequestPatientClinicalProfileHeightInches": ".preview_order_request_patient_clinical_profile_height_inches",
    "PreviewOrderRequestPatientClinicalProfileHeightInchesOne": ".preview_order_request_patient_clinical_profile_height_inches_one",
    "PreviewOrderRequestPatientClinicalProfileWeightPounds": ".preview_order_request_patient_clinical_profile_weight_pounds",
    "PreviewOrderRequestPatientClinicalProfileWeightPoundsOne": ".preview_order_request_patient_clinical_profile_weight_pounds_one",
    "PreviewOrderRequestPatientEncountersItem": ".preview_order_request_patient_encounters_item",
    "PreviewOrderRequestPatientExternalIdentitiesItem": ".preview_order_request_patient_external_identities_item",
    "PreviewOrderRequestPatientGender": ".preview_order_request_patient_gender",
    "PreviewOrderRequestPatientMeasurementsItem": ".preview_order_request_patient_measurements_item",
    "PreviewOrderRequestPatientMeasurementsItemHeightCentimeters": ".preview_order_request_patient_measurements_item_height_centimeters",
    "PreviewOrderRequestPatientMeasurementsItemHeightCentimetersOne": ".preview_order_request_patient_measurements_item_height_centimeters_one",
    "PreviewOrderRequestPatientMeasurementsItemWeightKilograms": ".preview_order_request_patient_measurements_item_weight_kilograms",
    "PreviewOrderRequestPatientMeasurementsItemWeightKilogramsOne": ".preview_order_request_patient_measurements_item_weight_kilograms_one",
    "PreviewOrderRequestPatientName": ".preview_order_request_patient_name",
    "PreviewOrderRequestPatientProgramsItem": ".preview_order_request_patient_programs_item",
    "PreviewOrderRequestPatientProgramsItemStatus": ".preview_order_request_patient_programs_item_status",
    "PreviewOrderRequestPrescriber": ".preview_order_request_prescriber",
    "PreviewOrderRequestPrescriberProfile": ".preview_order_request_prescriber_profile",
    "PreviewOrderRequestPrescriptionsItem": ".preview_order_request_prescriptions_item",
    "PreviewOrderRequestPrescriptionsItemOverrides": ".preview_order_request_prescriptions_item_overrides",
    "PreviewOrderRequestPrescriptionsItemOverridesClinical": ".preview_order_request_prescriptions_item_overrides_clinical",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason": ".preview_order_request_prescriptions_item_overrides_clinical_compounding_reason",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReasonCategory": ".preview_order_request_prescriptions_item_overrides_clinical_compounding_reason_category",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem": ".preview_order_request_prescriptions_item_overrides_clinical_diagnoses_item",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus": ".preview_order_request_prescriptions_item_overrides_clinical_diagnosis_review_status",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus": ".preview_order_request_prescriptions_item_overrides_clinical_medication_review_status",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem": ".preview_order_request_prescriptions_item_overrides_clinical_observations_item",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValue": ".preview_order_request_prescriptions_item_overrides_clinical_observations_item_value",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValueOne": ".preview_order_request_prescriptions_item_overrides_clinical_observations_item_value_one",
    "PreviewOrderRequestPrescriptionsItemOverridesDispensing": ".preview_order_request_prescriptions_item_overrides_dispensing",
    "PreviewOrderRequestPrescriptionsItemOverridesDispensingShippingDestinationType": ".preview_order_request_prescriptions_item_overrides_dispensing_shipping_destination_type",
    "PreviewOrderRequestPrescriptionsItemOverridesQuantity": ".preview_order_request_prescriptions_item_overrides_quantity",
    "PreviewOrderRequestPrescriptionsItemOverridesSig": ".preview_order_request_prescriptions_item_overrides_sig",
    "PreviewOrderRequestPrescriptionsItemOverridesSigFreeText": ".preview_order_request_prescriptions_item_overrides_sig_free_text",
    "PreviewOrderRequestPrescriptionsItemOverridesSigStructured": ".preview_order_request_prescriptions_item_overrides_sig_structured",
    "PreviewOrderRequestPrescriptionsItemOverridesSigStructuredFields": ".preview_order_request_prescriptions_item_overrides_sig_structured_fields",
    "PreviewOrderRequestPrescriptionsItemOverridesSigTemplate": ".preview_order_request_prescriptions_item_overrides_sig_template",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_FreeText": ".preview_order_request_prescriptions_item_overrides_sig",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_Structured": ".preview_order_request_prescriptions_item_overrides_sig",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_Template": ".preview_order_request_prescriptions_item_overrides_sig",
    "PreviewOrderRequestShipping": ".preview_order_request_shipping",
    "PreviewOrderRequestShippingSelection": ".preview_order_request_shipping_selection",
    "RejectOrderRequestExpectedVersionsItem": ".reject_order_request_expected_versions_item",
    "RejectOrderRequestPrescriber": ".reject_order_request_prescriber",
    "RejectOrderRequestPrescriberProfile": ".reject_order_request_prescriber_profile",
    "SignAndSubmitOrderRequestExpectedVersionsItem": ".sign_and_submit_order_request_expected_versions_item",
    "SignAndSubmitOrderRequestPrescriber": ".sign_and_submit_order_request_prescriber",
    "SignAndSubmitOrderRequestPrescriberProfile": ".sign_and_submit_order_request_prescriber_profile",
    "SignOrderRequestExpectedVersionsItem": ".sign_order_request_expected_versions_item",
    "SignOrderRequestPrescriber": ".sign_order_request_prescriber",
    "SignOrderRequestPrescriberProfile": ".sign_order_request_prescriber_profile",
    "SubmitOrderRequestPrescriber": ".submit_order_request_prescriber",
    "SubmitOrderRequestPrescriberProfile": ".submit_order_request_prescriber_profile",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateOrderRequestMetadataValue",
    "CreateOrderRequestOtcItemsItem",
    "CreateOrderRequestPatient",
    "CreateOrderRequestPatientAddress",
    "CreateOrderRequestPatientAddressCountry",
    "CreateOrderRequestPatientAddressesItem",
    "CreateOrderRequestPatientAddressesItemAddress",
    "CreateOrderRequestPatientAddressesItemAddressCountry",
    "CreateOrderRequestPatientClinicalProfile",
    "CreateOrderRequestPatientClinicalProfileHeightInches",
    "CreateOrderRequestPatientClinicalProfileHeightInchesOne",
    "CreateOrderRequestPatientClinicalProfileWeightPounds",
    "CreateOrderRequestPatientClinicalProfileWeightPoundsOne",
    "CreateOrderRequestPatientEncountersItem",
    "CreateOrderRequestPatientExternalIdentitiesItem",
    "CreateOrderRequestPatientGender",
    "CreateOrderRequestPatientMeasurementsItem",
    "CreateOrderRequestPatientMeasurementsItemHeightCentimeters",
    "CreateOrderRequestPatientMeasurementsItemHeightCentimetersOne",
    "CreateOrderRequestPatientMeasurementsItemWeightKilograms",
    "CreateOrderRequestPatientMeasurementsItemWeightKilogramsOne",
    "CreateOrderRequestPatientName",
    "CreateOrderRequestPatientProgramsItem",
    "CreateOrderRequestPatientProgramsItemStatus",
    "CreateOrderRequestPrescriber",
    "CreateOrderRequestPrescriberProfile",
    "CreateOrderRequestPrescriptionsItem",
    "CreateOrderRequestPrescriptionsItemClinical",
    "CreateOrderRequestPrescriptionsItemClinicalCompoundingReason",
    "CreateOrderRequestPrescriptionsItemClinicalCompoundingReasonCategory",
    "CreateOrderRequestPrescriptionsItemClinicalDiagnosesItem",
    "CreateOrderRequestPrescriptionsItemClinicalDiagnosisReviewStatus",
    "CreateOrderRequestPrescriptionsItemClinicalMedicationReviewStatus",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItem",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItemValue",
    "CreateOrderRequestPrescriptionsItemClinicalObservationsItemValueOne",
    "CreateOrderRequestPrescriptionsItemDispensing",
    "CreateOrderRequestPrescriptionsItemDispensingShippingDestinationType",
    "CreateOrderRequestPrescriptionsItemQuantity",
    "CreateOrderRequestPrescriptionsItemQuantityOne",
    "CreateOrderRequestPrescriptionsItemStructuredSig",
    "ListOrdersRequestSort",
    "ListOrdersRequestStatus",
    "PreviewOrderRequestOtcItemsItem",
    "PreviewOrderRequestPatient",
    "PreviewOrderRequestPatientAddress",
    "PreviewOrderRequestPatientAddressCountry",
    "PreviewOrderRequestPatientAddressesItem",
    "PreviewOrderRequestPatientAddressesItemAddress",
    "PreviewOrderRequestPatientAddressesItemAddressCountry",
    "PreviewOrderRequestPatientClinicalProfile",
    "PreviewOrderRequestPatientClinicalProfileHeightInches",
    "PreviewOrderRequestPatientClinicalProfileHeightInchesOne",
    "PreviewOrderRequestPatientClinicalProfileWeightPounds",
    "PreviewOrderRequestPatientClinicalProfileWeightPoundsOne",
    "PreviewOrderRequestPatientEncountersItem",
    "PreviewOrderRequestPatientExternalIdentitiesItem",
    "PreviewOrderRequestPatientGender",
    "PreviewOrderRequestPatientMeasurementsItem",
    "PreviewOrderRequestPatientMeasurementsItemHeightCentimeters",
    "PreviewOrderRequestPatientMeasurementsItemHeightCentimetersOne",
    "PreviewOrderRequestPatientMeasurementsItemWeightKilograms",
    "PreviewOrderRequestPatientMeasurementsItemWeightKilogramsOne",
    "PreviewOrderRequestPatientName",
    "PreviewOrderRequestPatientProgramsItem",
    "PreviewOrderRequestPatientProgramsItemStatus",
    "PreviewOrderRequestPrescriber",
    "PreviewOrderRequestPrescriberProfile",
    "PreviewOrderRequestPrescriptionsItem",
    "PreviewOrderRequestPrescriptionsItemOverrides",
    "PreviewOrderRequestPrescriptionsItemOverridesClinical",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReasonCategory",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValue",
    "PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItemValueOne",
    "PreviewOrderRequestPrescriptionsItemOverridesDispensing",
    "PreviewOrderRequestPrescriptionsItemOverridesDispensingShippingDestinationType",
    "PreviewOrderRequestPrescriptionsItemOverridesQuantity",
    "PreviewOrderRequestPrescriptionsItemOverridesSig",
    "PreviewOrderRequestPrescriptionsItemOverridesSigFreeText",
    "PreviewOrderRequestPrescriptionsItemOverridesSigStructured",
    "PreviewOrderRequestPrescriptionsItemOverridesSigStructuredFields",
    "PreviewOrderRequestPrescriptionsItemOverridesSigTemplate",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_FreeText",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_Structured",
    "PreviewOrderRequestPrescriptionsItemOverridesSig_Template",
    "PreviewOrderRequestShipping",
    "PreviewOrderRequestShippingSelection",
    "RejectOrderRequestExpectedVersionsItem",
    "RejectOrderRequestPrescriber",
    "RejectOrderRequestPrescriberProfile",
    "SignAndSubmitOrderRequestExpectedVersionsItem",
    "SignAndSubmitOrderRequestPrescriber",
    "SignAndSubmitOrderRequestPrescriberProfile",
    "SignOrderRequestExpectedVersionsItem",
    "SignOrderRequestPrescriber",
    "SignOrderRequestPrescriberProfile",
    "SubmitOrderRequestPrescriber",
    "SubmitOrderRequestPrescriberProfile",
]
