# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_order_request_prescriptions_item_clinical_compounding_reason import (
    CreateOrderRequestPrescriptionsItemClinicalCompoundingReason,
)
from .create_order_request_prescriptions_item_clinical_diagnoses_item import (
    CreateOrderRequestPrescriptionsItemClinicalDiagnosesItem,
)
from .create_order_request_prescriptions_item_clinical_diagnosis_review_status import (
    CreateOrderRequestPrescriptionsItemClinicalDiagnosisReviewStatus,
)
from .create_order_request_prescriptions_item_clinical_medication_review_status import (
    CreateOrderRequestPrescriptionsItemClinicalMedicationReviewStatus,
)
from .create_order_request_prescriptions_item_clinical_observations_item import (
    CreateOrderRequestPrescriptionsItemClinicalObservationsItem,
)


class CreateOrderRequestPrescriptionsItemClinical(UniversalBaseModel):
    compounding_reason: typing_extensions.Annotated[
        typing.Optional[CreateOrderRequestPrescriptionsItemClinicalCompoundingReason],
        FieldMetadata(alias="compoundingReason"),
        pydantic.Field(alias="compoundingReason"),
    ] = None
    medication_review_status: typing_extensions.Annotated[
        typing.Optional[CreateOrderRequestPrescriptionsItemClinicalMedicationReviewStatus],
        FieldMetadata(alias="medicationReviewStatus"),
        pydantic.Field(alias="medicationReviewStatus"),
    ] = None
    diagnosis_review_status: typing_extensions.Annotated[
        typing.Optional[CreateOrderRequestPrescriptionsItemClinicalDiagnosisReviewStatus],
        FieldMetadata(alias="diagnosisReviewStatus"),
        pydantic.Field(alias="diagnosisReviewStatus"),
    ] = None
    current_medications: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="currentMedications"),
        pydantic.Field(alias="currentMedications"),
    ] = None
    diagnoses: typing.Optional[typing.List[CreateOrderRequestPrescriptionsItemClinicalDiagnosesItem]] = None
    observations: typing.Optional[typing.List[CreateOrderRequestPrescriptionsItemClinicalObservationsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
