# This file was auto-generated by Fern from our API Definition.

import typing

from .create_order_batch_request_orders_item_patient_measurements_item_weight_kilograms_one import (
    CreateOrderBatchRequestOrdersItemPatientMeasurementsItemWeightKilogramsOne,
)

CreateOrderBatchRequestOrdersItemPatientMeasurementsItemWeightKilograms = typing.Union[
    float, CreateOrderBatchRequestOrdersItemPatientMeasurementsItemWeightKilogramsOne
]
