# This file was auto-generated by Fern from our API Definition.

import typing

UpdateOrderTestSimulationRequestScenario = typing.Union[
    typing.Literal["successful", "pharmacy_rejection", "cancellation_declined"], typing.Any
]
