# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_order_batch_request_orders_item_prescriptions_item_clinical_observations_item_value import (
    CreateOrderBatchRequestOrdersItemPrescriptionsItemClinicalObservationsItemValue,
)


class CreateOrderBatchRequestOrdersItemPrescriptionsItemClinicalObservationsItem(UniversalBaseModel):
    display: str
    unit: str
    value: CreateOrderBatchRequestOrdersItemPrescriptionsItemClinicalObservationsItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
