# This file was auto-generated by Fern from our API Definition.

import typing

from .create_order_batch_request_orders_item_patient_clinical_profile_height_inches_one import (
    CreateOrderBatchRequestOrdersItemPatientClinicalProfileHeightInchesOne,
)

CreateOrderBatchRequestOrdersItemPatientClinicalProfileHeightInches = typing.Union[
    float, CreateOrderBatchRequestOrdersItemPatientClinicalProfileHeightInchesOne
]
