# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.archive_practice_location_response import ArchivePracticeLocationResponse
from ..types.create_practice_location_response import CreatePracticeLocationResponse
from ..types.get_practice_location_response import GetPracticeLocationResponse
from ..types.list_practice_locations_response import ListPracticeLocationsResponse
from ..types.update_practice_location_response import UpdatePracticeLocationResponse
from .raw_client import AsyncRawLocationsClient, RawLocationsClient
from .types.list_locations_request_status import ListLocationsRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LocationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLocationsClient
        """
        return self._raw_client

    def list(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        status: typing.Optional[ListLocationsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeLocationsResponse:
        """
        Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        status : typing.Optional[ListLocationsRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeLocationsResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.locations.list(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            starting_after="loc_01j2y8m6jcc9tt24af5pw9x1bc",
            ending_before="loc_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.list(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        practice_id: str,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.

        Parameters
        ----------
        practice_id : str

        name : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        city : typing.Optional[str]

        country : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        phone : typing.Optional[str]

        postal_code : typing.Optional[str]

        state : typing.Optional[str]

        timezone : typing.Optional[str]
            Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePracticeLocationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.locations.create(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            name="name",
        )
        """
        _response = self._raw_client.create(
            practice_id,
            name=name,
            idempotency_key=idempotency_key,
            city=city,
            country=country,
            line1=line1,
            line2=line2,
            phone=phone,
            postal_code=postal_code,
            state=state,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, practice_id: str, location_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeLocationResponse:
        """
        Requires locations:read. Returns one active or archived location in the authorized practice.

        Parameters
        ----------
        practice_id : str

        location_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeLocationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.locations.get(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get(practice_id, location_id, request_options=request_options)
        return _response.data

    def update(
        self,
        practice_id: str,
        location_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.

        Parameters
        ----------
        practice_id : str

        location_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        city : typing.Optional[str]

        country : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        name : typing.Optional[str]

        phone : typing.Optional[str]

        postal_code : typing.Optional[str]

        state : typing.Optional[str]

        timezone : typing.Optional[str]
            Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeLocationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.locations.update(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.update(
            practice_id,
            location_id,
            idempotency_key=idempotency_key,
            city=city,
            country=country,
            line1=line1,
            line2=line2,
            name=name,
            phone=phone,
            postal_code=postal_code,
            state=state,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    def archive(
        self,
        practice_id: str,
        location_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ArchivePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.

        Parameters
        ----------
        practice_id : str

        location_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ArchivePracticeLocationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.locations.archive(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.archive(
            practice_id, location_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncLocationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLocationsClient
        """
        return self._raw_client

    async def list(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        status: typing.Optional[ListLocationsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeLocationsResponse:
        """
        Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        status : typing.Optional[ListLocationsRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeLocationsResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.locations.list(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                starting_after="loc_01j2y8m6jcc9tt24af5pw9x1bc",
                ending_before="loc_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        practice_id: str,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.

        Parameters
        ----------
        practice_id : str

        name : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        city : typing.Optional[str]

        country : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        phone : typing.Optional[str]

        postal_code : typing.Optional[str]

        state : typing.Optional[str]

        timezone : typing.Optional[str]
            Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePracticeLocationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.locations.create(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            practice_id,
            name=name,
            idempotency_key=idempotency_key,
            city=city,
            country=country,
            line1=line1,
            line2=line2,
            phone=phone,
            postal_code=postal_code,
            state=state,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, practice_id: str, location_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeLocationResponse:
        """
        Requires locations:read. Returns one active or archived location in the authorized practice.

        Parameters
        ----------
        practice_id : str

        location_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeLocationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.locations.get(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(practice_id, location_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        practice_id: str,
        location_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.

        Parameters
        ----------
        practice_id : str

        location_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        city : typing.Optional[str]

        country : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        name : typing.Optional[str]

        phone : typing.Optional[str]

        postal_code : typing.Optional[str]

        state : typing.Optional[str]

        timezone : typing.Optional[str]
            Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeLocationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.locations.update(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            practice_id,
            location_id,
            idempotency_key=idempotency_key,
            city=city,
            country=country,
            line1=line1,
            line2=line2,
            name=name,
            phone=phone,
            postal_code=postal_code,
            state=state,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    async def archive(
        self,
        practice_id: str,
        location_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ArchivePracticeLocationResponse:
        """
        Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.

        Parameters
        ----------
        practice_id : str

        location_id : str

        idempotency_key : typing.Optional[str]
            Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ArchivePracticeLocationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.locations.archive(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                location_id="loc_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.archive(
            practice_id, location_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
