# This file was auto-generated by Fern from our API Definition.

import typing

ReplacePatientAllergiesRequestAllergiesItemCategory = typing.Union[
    typing.Literal["drug", "food", "insect", "latex", "mold", "pet", "pollen", "environmental", "biologic", "other"],
    typing.Any,
]
