# This file was auto-generated by Fern from our API Definition.

import typing

from .update_patient_request_measurements_item_weight_kilograms_one import (
    UpdatePatientRequestMeasurementsItemWeightKilogramsOne,
)

UpdatePatientRequestMeasurementsItemWeightKilograms = typing.Union[
    float, UpdatePatientRequestMeasurementsItemWeightKilogramsOne
]
