# This file was auto-generated by Fern from our API Definition.

import typing

from .update_patient_request_measurements_item_height_centimeters_one import (
    UpdatePatientRequestMeasurementsItemHeightCentimetersOne,
)

UpdatePatientRequestMeasurementsItemHeightCentimeters = typing.Union[
    float, UpdatePatientRequestMeasurementsItemHeightCentimetersOne
]
