# This file was auto-generated by Fern from our API Definition.

import typing

CancelOrderResponseFulfillmentsItemShipmentsItemSource = typing.Union[
    typing.Literal["pharmacy_webhook", "pharmacy", "system"], typing.Any
]
