# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cancel_order_response_cancellation_outcomes_item_status import CancelOrderResponseCancellationOutcomesItemStatus


class CancelOrderResponseCancellationOutcomesItem(UniversalBaseModel):
    cancellation_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="cancellationId"), pydantic.Field(alias="cancellationId")
    ]
    fulfillment_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="fulfillmentId"), pydantic.Field(alias="fulfillmentId")
    ]
    status: CancelOrderResponseCancellationOutcomesItemStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
