# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cancel_order_response_cancellation_outcomes_item import CancelOrderResponseCancellationOutcomesItem
from .cancel_order_response_cancellation_status import CancelOrderResponseCancellationStatus


class CancelOrderResponseCancellation(UniversalBaseModel):
    status: CancelOrderResponseCancellationStatus
    outcomes: typing.List[CancelOrderResponseCancellationOutcomesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
