# This file was auto-generated by Fern from our API Definition.

import typing

from .create_patient_response_measurements_item_weight_kilograms_one import (
    CreatePatientResponseMeasurementsItemWeightKilogramsOne,
)

CreatePatientResponseMeasurementsItemWeightKilograms = typing.Union[
    float, CreatePatientResponseMeasurementsItemWeightKilogramsOne
]
