# This file was auto-generated by Fern from our API Definition.

import typing

from .get_practice_team_response_members_active_one import GetPracticeTeamResponseMembersActiveOne

GetPracticeTeamResponseMembersActive = typing.Union[float, GetPracticeTeamResponseMembersActiveOne]
