# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .get_order_response_fulfillments_item_shipping_destination_type import (
    GetOrderResponseFulfillmentsItemShippingDestinationType,
)
from .get_order_response_fulfillments_item_shipping_method import GetOrderResponseFulfillmentsItemShippingMethod
from .get_order_response_fulfillments_item_shipping_option import GetOrderResponseFulfillmentsItemShippingOption


class GetOrderResponseFulfillmentsItemShipping(UniversalBaseModel):
    destination_type: typing_extensions.Annotated[
        GetOrderResponseFulfillmentsItemShippingDestinationType,
        FieldMetadata(alias="destinationType"),
        pydantic.Field(alias="destinationType"),
    ]
    method: GetOrderResponseFulfillmentsItemShippingMethod
    option: typing.Optional[GetOrderResponseFulfillmentsItemShippingOption] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
