# This file was auto-generated by Fern from our API Definition.

import typing

GetOrderResponseFulfillmentsItemExceptionsItemSeverity = typing.Union[typing.Literal["warning", "critical"], typing.Any]
