# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GetOrderResponseOtcItemsItem(UniversalBaseModel):
    catalog_item_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="catalogItemId"), pydantic.Field(alias="catalogItemId")
    ]
    prescription_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="prescriptionId"), pydantic.Field(alias="prescriptionId")
    ]
    name: str
    quantity: int
    unit_price_cents: typing_extensions.Annotated[
        int, FieldMetadata(alias="unitPriceCents"), pydantic.Field(alias="unitPriceCents")
    ]
    subtotal_cents: typing_extensions.Annotated[
        int, FieldMetadata(alias="subtotalCents"), pydantic.Field(alias="subtotalCents")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
