# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_practice_response_contacts_compliance import GetPracticeResponseContactsCompliance
from .get_practice_response_contacts_primary import GetPracticeResponseContactsPrimary


class GetPracticeResponseContacts(UniversalBaseModel):
    compliance: typing.Optional[GetPracticeResponseContactsCompliance] = None
    primary: typing.Optional[GetPracticeResponseContactsPrimary] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
