# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .get_api_access_response_api_key import GetApiAccessResponseApiKey
from .get_api_access_response_object import GetApiAccessResponseObject
from .get_api_access_response_service_account import GetApiAccessResponseServiceAccount


class GetApiAccessResponse(UniversalBaseModel):
    api_key: typing_extensions.Annotated[
        GetApiAccessResponseApiKey, FieldMetadata(alias="apiKey"), pydantic.Field(alias="apiKey")
    ]
    livemode: bool
    object: GetApiAccessResponseObject
    scopes: typing.List[str]
    service_account: typing_extensions.Annotated[
        GetApiAccessResponseServiceAccount,
        FieldMetadata(alias="serviceAccount"),
        pydantic.Field(alias="serviceAccount"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
