# This file was auto-generated by Fern from our API Definition.

import typing

GetPatientAllergiesResponseReviewStatus = typing.Union[
    typing.Literal["not_reviewed", "no_known", "recorded"], typing.Any
]
