# This file was auto-generated by Fern from our API Definition.

import typing

ListOrdersResponseDataItemPrescriptionsItemPatientSnapshotGender = typing.Union[
    typing.Literal["f", "m", "o", "u"], typing.Any
]
