# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_pharmacies_response_data_item_profile_rating import ListPharmaciesResponseDataItemProfileRating


class ListPharmaciesResponseDataItemProfile(UniversalBaseModel):
    description: str
    effective_at: typing_extensions.Annotated[
        str, FieldMetadata(alias="effectiveAt"), pydantic.Field(alias="effectiveAt")
    ]
    monthly_prescription_volume: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="monthlyPrescriptionVolume"),
        pydantic.Field(alias="monthlyPrescriptionVolume"),
    ] = None
    rating: typing.Optional[ListPharmaciesResponseDataItemProfileRating] = None
    rating_basis: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ratingBasis"), pydantic.Field(alias="ratingBasis")
    ] = None
    rating_review_count: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="ratingReviewCount"), pydantic.Field(alias="ratingReviewCount")
    ] = None
    recommended_rank: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="recommendedRank"), pydantic.Field(alias="recommendedRank")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
