# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_orders_response_data_item_fulfillments_item_shipments_item_source import (
    ListOrdersResponseDataItemFulfillmentsItemShipmentsItemSource,
)
from .list_orders_response_data_item_fulfillments_item_shipments_item_status import (
    ListOrdersResponseDataItemFulfillmentsItemShipmentsItemStatus,
)


class ListOrdersResponseDataItemFulfillmentsItemShipmentsItem(UniversalBaseModel):
    carrier: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    delivered_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="deliveredAt"), pydantic.Field(alias="deliveredAt")
    ] = None
    estimated_delivery_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="estimatedDeliveryAt"), pydantic.Field(alias="estimatedDeliveryAt")
    ] = None
    id: str
    is_active: typing_extensions.Annotated[bool, FieldMetadata(alias="isActive"), pydantic.Field(alias="isActive")]
    provider_status: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="providerStatus"), pydantic.Field(alias="providerStatus")
    ] = None
    replaced_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="replacedAt"), pydantic.Field(alias="replacedAt")
    ] = None
    replaces_shipment_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="replacesShipmentId"), pydantic.Field(alias="replacesShipmentId")
    ] = None
    shipped_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="shippedAt"), pydantic.Field(alias="shippedAt")
    ] = None
    source: ListOrdersResponseDataItemFulfillmentsItemShipmentsItemSource
    status: ListOrdersResponseDataItemFulfillmentsItemShipmentsItemStatus
    tracking_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="trackingNumber"), pydantic.Field(alias="trackingNumber")
    ] = None
    tracking_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="trackingUrl"), pydantic.Field(alias="trackingUrl")
    ] = None
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]
    voided_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="voidedAt"), pydantic.Field(alias="voidedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
