# This file was auto-generated by Fern from our API Definition.

import typing

ListCatalogItemsResponseDataItemOrderingShipping = typing.Union[
    typing.Literal["prescription", "accompanying_prescription"], typing.Any
]
