# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_orders_response_data_item_prescriptions_item_clinical_allergies_item_reactions_item import (
    ListOrdersResponseDataItemPrescriptionsItemClinicalAllergiesItemReactionsItem,
)


class ListOrdersResponseDataItemPrescriptionsItemClinicalAllergiesItem(UniversalBaseModel):
    code: typing.Optional[str] = None
    code_system: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="codeSystem"), pydantic.Field(alias="codeSystem")
    ] = None
    display: str
    source: typing.Optional[str] = None
    category: typing.Optional[str] = None
    severity: typing.Optional[str] = None
    type: typing.Optional[str] = None
    verification_status: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="verificationStatus"), pydantic.Field(alias="verificationStatus")
    ] = None
    reactions: typing.Optional[
        typing.List[ListOrdersResponseDataItemPrescriptionsItemClinicalAllergiesItemReactionsItem]
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
