# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_pharmacies_response_data_item_access import ListPharmaciesResponseDataItemAccess
from .list_pharmacies_response_data_item_facility_locations_item import (
    ListPharmaciesResponseDataItemFacilityLocationsItem,
)
from .list_pharmacies_response_data_item_object import ListPharmaciesResponseDataItemObject
from .list_pharmacies_response_data_item_profile import ListPharmaciesResponseDataItemProfile
from .list_pharmacies_response_data_item_shipping_options_item import ListPharmaciesResponseDataItemShippingOptionsItem


class ListPharmaciesResponseDataItem(UniversalBaseModel):
    access: ListPharmaciesResponseDataItemAccess
    catalog_item_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="catalogItemCount"), pydantic.Field(alias="catalogItemCount")
    ]
    facility_type: typing_extensions.Annotated[
        str, FieldMetadata(alias="facilityType"), pydantic.Field(alias="facilityType")
    ]
    facility_locations: typing_extensions.Annotated[
        typing.List[ListPharmaciesResponseDataItemFacilityLocationsItem],
        FieldMetadata(alias="facilityLocations"),
        pydantic.Field(alias="facilityLocations"),
    ]
    id: str
    livemode: bool
    logo_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="logoUrl"), pydantic.Field(alias="logoUrl")
    ] = None
    name: str
    object: ListPharmaciesResponseDataItemObject
    prescriptions_last30days: typing_extensions.Annotated[
        int, FieldMetadata(alias="prescriptionsLast30Days"), pydantic.Field(alias="prescriptionsLast30Days")
    ]
    profile: typing.Optional[ListPharmaciesResponseDataItemProfile] = None
    restricted_states: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="restrictedStates"), pydantic.Field(alias="restrictedStates")
    ]
    shipping_options: typing_extensions.Annotated[
        typing.List[ListPharmaciesResponseDataItemShippingOptionsItem],
        FieldMetadata(alias="shippingOptions"),
        pydantic.Field(alias="shippingOptions"),
    ]
    supported_states: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="supportedStates"), pydantic.Field(alias="supportedStates")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
