# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_practice_team_invitations_response_data_item import ListPracticeTeamInvitationsResponseDataItem
from .list_practice_team_invitations_response_object import ListPracticeTeamInvitationsResponseObject


class ListPracticeTeamInvitationsResponse(UniversalBaseModel):
    data: typing.List[ListPracticeTeamInvitationsResponseDataItem]
    has_more: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMore"), pydantic.Field(alias="hasMore")]
    object: ListPracticeTeamInvitationsResponseObject
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
