# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_practice_team_invitations_response_data_item_person_invitation_roles_item import (
    ListPracticeTeamInvitationsResponseDataItemPersonInvitationRolesItem,
)
from .list_practice_team_invitations_response_data_item_person_invitation_status import (
    ListPracticeTeamInvitationsResponseDataItemPersonInvitationStatus,
)


class ListPracticeTeamInvitationsResponseDataItemPersonInvitation(UniversalBaseModel):
    id: str
    status: ListPracticeTeamInvitationsResponseDataItemPersonInvitationStatus
    expires_at: typing_extensions.Annotated[str, FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")]
    roles: typing.List[ListPracticeTeamInvitationsResponseDataItemPersonInvitationRolesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
