# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .preview_order_response_order_input_patient_addresses_item_address_country import (
    PreviewOrderResponseOrderInputPatientAddressesItemAddressCountry,
)


class PreviewOrderResponseOrderInputPatientAddressesItemAddress(UniversalBaseModel):
    city: str
    country: typing.Optional[PreviewOrderResponseOrderInputPatientAddressesItemAddressCountry] = None
    line1: str
    line2: typing.Optional[str] = None
    postal_code: typing_extensions.Annotated[str, FieldMetadata(alias="postalCode"), pydantic.Field(alias="postalCode")]
    state: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
