# This file was auto-generated by Fern from our API Definition.

import typing

RetrievePrescribingOptionsResponseCatalogCompositionIngredientsItemRole = typing.Union[
    typing.Literal["active", "inactive"], typing.Any
]
