# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .retrieve_prescribing_options_response_catalog_catalog_details_attributes_value import (
    RetrievePrescribingOptionsResponseCatalogCatalogDetailsAttributesValue,
)
from .retrieve_prescribing_options_response_catalog_catalog_details_directions_item import (
    RetrievePrescribingOptionsResponseCatalogCatalogDetailsDirectionsItem,
)
from .retrieve_prescribing_options_response_catalog_catalog_details_package_components_item import (
    RetrievePrescribingOptionsResponseCatalogCatalogDetailsPackageComponentsItem,
)


class RetrievePrescribingOptionsResponseCatalogCatalogDetails(UniversalBaseModel):
    package_components: typing_extensions.Annotated[
        typing.Optional[typing.List[RetrievePrescribingOptionsResponseCatalogCatalogDetailsPackageComponentsItem]],
        FieldMetadata(alias="packageComponents"),
        pydantic.Field(
            alias="packageComponents",
            description="Confirmed physical containers and contents. Empty or absent means container count cannot be inferred from dispense quantity.",
        ),
    ] = None
    """
    Confirmed physical containers and contents. Empty or absent means container count cannot be inferred from dispense quantity.
    """

    attributes: typing.Dict[str, RetrievePrescribingOptionsResponseCatalogCatalogDetailsAttributesValue]
    directions: typing.List[RetrievePrescribingOptionsResponseCatalogCatalogDetailsDirectionsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
