# This file was auto-generated by Fern from our API Definition.

import typing

RetrievePrescribingOptionsResponseCatalogCompositionStatus = typing.Union[
    typing.Literal["complete", "partial", "unresolved"], typing.Any
]
