# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .retrieve_prescribing_options_response_catalog_pricing_basis_item_quantity import (
    RetrievePrescribingOptionsResponseCatalogPricingBasisItemQuantity,
)
from .retrieve_prescribing_options_response_catalog_pricing_basis_item_quantity_prices_item import (
    RetrievePrescribingOptionsResponseCatalogPricingBasisItemQuantityPricesItem,
)
from .retrieve_prescribing_options_response_catalog_pricing_basis_unit_quantity import (
    RetrievePrescribingOptionsResponseCatalogPricingBasisUnitQuantity,
)


class RetrievePrescribingOptionsResponseCatalogPricingBasis_Item(UniversalBaseModel):
    kind: typing.Literal["item"] = "item"
    quantity: RetrievePrescribingOptionsResponseCatalogPricingBasisItemQuantity
    unit: str
    quantity_prices: typing_extensions.Annotated[
        typing.Optional[typing.List[RetrievePrescribingOptionsResponseCatalogPricingBasisItemQuantityPricesItem]],
        FieldMetadata(alias="quantityPrices"),
        pydantic.Field(alias="quantityPrices"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RetrievePrescribingOptionsResponseCatalogPricingBasis_Package(UniversalBaseModel):
    kind: typing.Literal["package"] = "package"
    quantity: str
    unit: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RetrievePrescribingOptionsResponseCatalogPricingBasis_Unit(UniversalBaseModel):
    kind: typing.Literal["unit"] = "unit"
    quantity: RetrievePrescribingOptionsResponseCatalogPricingBasisUnitQuantity
    unit: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


RetrievePrescribingOptionsResponseCatalogPricingBasis = typing_extensions.Annotated[
    typing.Union[
        RetrievePrescribingOptionsResponseCatalogPricingBasis_Item,
        RetrievePrescribingOptionsResponseCatalogPricingBasis_Package,
        RetrievePrescribingOptionsResponseCatalogPricingBasis_Unit,
    ],
    pydantic.Field(discriminator="kind"),
]
