# This file was auto-generated by Fern from our API Definition.

import typing

RetrievePrescribingOptionsResponsePresetsItemSource = typing.Union[
    typing.Literal["affinity", "pharmacy", "catalog"], typing.Any
]
