# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieve_prescribing_options_response_medication_rxnorm import RetrievePrescribingOptionsResponseMedicationRxnorm


class RetrievePrescribingOptionsResponseMedication(UniversalBaseModel):
    name: str
    rxnorm: typing.Optional[RetrievePrescribingOptionsResponseMedicationRxnorm] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
