# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .revoke_practice_team_invitation_response_object import RevokePracticeTeamInvitationResponseObject
from .revoke_practice_team_invitation_response_person import RevokePracticeTeamInvitationResponsePerson
from .revoke_practice_team_invitation_response_roles_item import RevokePracticeTeamInvitationResponseRolesItem
from .revoke_practice_team_invitation_response_status import RevokePracticeTeamInvitationResponseStatus


class RevokePracticeTeamInvitationResponse(UniversalBaseModel):
    id: str
    object: RevokePracticeTeamInvitationResponseObject
    email: str
    name: typing.Optional[str] = None
    status: RevokePracticeTeamInvitationResponseStatus
    roles: typing.List[RevokePracticeTeamInvitationResponseRolesItem]
    location_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="locationIds"), pydantic.Field(alias="locationIds")
    ]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    expires_at: typing_extensions.Annotated[str, FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")]
    accepted_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="acceptedAt"), pydantic.Field(alias="acceptedAt")
    ] = None
    user_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="userId"),
        pydantic.Field(
            alias="userId",
            description="This integration's mode-scoped user ID, used for draft attribution and sessions after acceptance. Null for invitations outside this integration.",
        ),
    ] = None
    """
    This integration's mode-scoped user ID, used for draft attribution and sessions after acceptance. Null for invitations outside this integration.
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    member_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="memberId"), pydantic.Field(alias="memberId")
    ] = None
    prescriber_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="prescriberId"), pydantic.Field(alias="prescriberId")
    ] = None
    person: typing.Optional[RevokePracticeTeamInvitationResponsePerson] = pydantic.Field(default=None)
    """
    This integration's current onboarding and account-connection state. Null for invitations outside this integration.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
