# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_webhook_endpoint_response_object import UpdateWebhookEndpointResponseObject
from .update_webhook_endpoint_response_payload_style import UpdateWebhookEndpointResponsePayloadStyle
from .update_webhook_endpoint_response_status import UpdateWebhookEndpointResponseStatus


class UpdateWebhookEndpointResponse(UniversalBaseModel):
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    practice_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="practiceIds"), pydantic.Field(alias="practiceIds")
    ]
    api_version: typing_extensions.Annotated[str, FieldMetadata(alias="apiVersion"), pydantic.Field(alias="apiVersion")]
    consecutive_failures: typing_extensions.Annotated[
        int, FieldMetadata(alias="consecutiveFailures"), pydantic.Field(alias="consecutiveFailures")
    ]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    description: str
    id: str
    livemode: bool
    object: UpdateWebhookEndpointResponseObject
    payload_style: typing_extensions.Annotated[
        UpdateWebhookEndpointResponsePayloadStyle,
        FieldMetadata(alias="payloadStyle"),
        pydantic.Field(alias="payloadStyle"),
    ]
    status: UpdateWebhookEndpointResponseStatus
    subscribed_events: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="subscribedEvents"), pydantic.Field(alias="subscribedEvents")
    ]
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
