# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_practice_response_contacts_compliance import UpdatePracticeResponseContactsCompliance
from .update_practice_response_contacts_primary import UpdatePracticeResponseContactsPrimary


class UpdatePracticeResponseContacts(UniversalBaseModel):
    compliance: typing.Optional[UpdatePracticeResponseContactsCompliance] = None
    primary: typing.Optional[UpdatePracticeResponseContactsPrimary] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
