# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_practice_team_member_response_account_prescriber_connection_provider_address import (
    UpdatePracticeTeamMemberResponseAccountPrescriberConnectionProviderAddress,
)
from .update_practice_team_member_response_account_prescriber_connection_provider_licenses_item import (
    UpdatePracticeTeamMemberResponseAccountPrescriberConnectionProviderLicensesItem,
)


class UpdatePracticeTeamMemberResponseAccountPrescriberConnectionProvider(UniversalBaseModel):
    id: str
    name: str
    legal_name: typing_extensions.Annotated[str, FieldMetadata(alias="legalName"), pydantic.Field(alias="legalName")]
    credentials: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    address: typing.Optional[UpdatePracticeTeamMemberResponseAccountPrescriberConnectionProviderAddress] = None
    npi: str
    practice_status: typing_extensions.Annotated[
        str, FieldMetadata(alias="practiceStatus"), pydantic.Field(alias="practiceStatus")
    ]
    licenses: typing.List[UpdatePracticeTeamMemberResponseAccountPrescriberConnectionProviderLicensesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
