# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_patient_response_address import UpdatePatientResponseAddress
from .update_patient_response_addresses_item import UpdatePatientResponseAddressesItem
from .update_patient_response_allergy_review_status import UpdatePatientResponseAllergyReviewStatus
from .update_patient_response_allergy_summary_item import UpdatePatientResponseAllergySummaryItem
from .update_patient_response_clinical_profile import UpdatePatientResponseClinicalProfile
from .update_patient_response_encounters_item import UpdatePatientResponseEncountersItem
from .update_patient_response_external_identities_item import UpdatePatientResponseExternalIdentitiesItem
from .update_patient_response_gender import UpdatePatientResponseGender
from .update_patient_response_location import UpdatePatientResponseLocation
from .update_patient_response_measurements_item import UpdatePatientResponseMeasurementsItem
from .update_patient_response_name import UpdatePatientResponseName
from .update_patient_response_object import UpdatePatientResponseObject
from .update_patient_response_programs_item import UpdatePatientResponseProgramsItem
from .update_patient_response_shipping_address import UpdatePatientResponseShippingAddress
from .update_patient_response_status import UpdatePatientResponseStatus


class UpdatePatientResponse(UniversalBaseModel):
    address: typing.Optional[UpdatePatientResponseAddress] = None
    default_shipping_address_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultShippingAddressId"),
        pydantic.Field(alias="defaultShippingAddressId"),
    ] = None
    shipping_address: typing_extensions.Annotated[
        typing.Optional[UpdatePatientResponseShippingAddress],
        FieldMetadata(alias="shippingAddress"),
        pydantic.Field(alias="shippingAddress"),
    ] = None
    allergy_review_status: typing_extensions.Annotated[
        UpdatePatientResponseAllergyReviewStatus,
        FieldMetadata(alias="allergyReviewStatus"),
        pydantic.Field(alias="allergyReviewStatus"),
    ]
    allergy_summary: typing_extensions.Annotated[
        typing.List[UpdatePatientResponseAllergySummaryItem],
        FieldMetadata(alias="allergySummary"),
        pydantic.Field(alias="allergySummary"),
    ]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    clinical_profile: typing_extensions.Annotated[
        UpdatePatientResponseClinicalProfile,
        FieldMetadata(alias="clinicalProfile"),
        pydantic.Field(alias="clinicalProfile"),
    ]
    date_of_birth: typing_extensions.Annotated[
        str, FieldMetadata(alias="dateOfBirth"), pydantic.Field(alias="dateOfBirth")
    ]
    email: typing.Optional[str] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    external_identities: typing_extensions.Annotated[
        typing.List[UpdatePatientResponseExternalIdentitiesItem],
        FieldMetadata(alias="externalIdentities"),
        pydantic.Field(alias="externalIdentities"),
    ]
    addresses: typing.List[UpdatePatientResponseAddressesItem]
    encounters: typing.List[UpdatePatientResponseEncountersItem]
    gender: UpdatePatientResponseGender
    id: str
    livemode: bool
    location: UpdatePatientResponseLocation
    location_id: typing_extensions.Annotated[str, FieldMetadata(alias="locationId"), pydantic.Field(alias="locationId")]
    metadata: typing.Dict[str, typing.Any]
    medical_record_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="medicalRecordNumber"), pydantic.Field(alias="medicalRecordNumber")
    ] = None
    measurements: typing.List[UpdatePatientResponseMeasurementsItem]
    name: UpdatePatientResponseName
    object: UpdatePatientResponseObject
    phone: typing.Optional[str] = None
    programs: typing.List[UpdatePatientResponseProgramsItem]
    practice_id: typing_extensions.Annotated[str, FieldMetadata(alias="practiceId"), pydantic.Field(alias="practiceId")]
    status: UpdatePatientResponseStatus
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
