# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_practice_team_license_response import CreatePracticeTeamLicenseResponse
from ..types.get_practice_team_invitation_response import GetPracticeTeamInvitationResponse
from ..types.get_practice_team_member_response import GetPracticeTeamMemberResponse
from ..types.get_practice_team_prescriber_response import GetPracticeTeamPrescriberResponse
from ..types.get_practice_team_response import GetPracticeTeamResponse
from ..types.invite_practice_team_person_response import InvitePracticeTeamPersonResponse
from ..types.list_practice_team_invitations_response import ListPracticeTeamInvitationsResponse
from ..types.list_practice_team_members_response import ListPracticeTeamMembersResponse
from ..types.list_practice_team_prescribers_response import ListPracticeTeamPrescribersResponse
from ..types.register_user_response import RegisterUserResponse
from ..types.resend_practice_team_invitation_response import ResendPracticeTeamInvitationResponse
from ..types.revoke_practice_team_invitation_response import RevokePracticeTeamInvitationResponse
from ..types.update_practice_team_license_response import UpdatePracticeTeamLicenseResponse
from ..types.update_practice_team_member_response import UpdatePracticeTeamMemberResponse
from ..types.update_practice_team_prescriber_response import UpdatePracticeTeamPrescriberResponse
from .raw_client import AsyncRawTeamClient, RawTeamClient
from .types.invite_practice_team_person_request_address import InvitePracticeTeamPersonRequestAddress
from .types.invite_practice_team_person_request_licenses_item import InvitePracticeTeamPersonRequestLicensesItem
from .types.invite_practice_team_person_request_profile_details import InvitePracticeTeamPersonRequestProfileDetails
from .types.invite_practice_team_person_request_role import InvitePracticeTeamPersonRequestRole
from .types.invite_practice_team_person_request_roles_item import InvitePracticeTeamPersonRequestRolesItem
from .types.list_practice_team_invitations_request_status import ListPracticeTeamInvitationsRequestStatus
from .types.list_practice_team_members_request_role import ListPracticeTeamMembersRequestRole
from .types.list_practice_team_members_request_status import ListPracticeTeamMembersRequestStatus
from .types.list_practice_team_prescribers_request_status import ListPracticeTeamPrescribersRequestStatus
from .types.register_user_request_address import RegisterUserRequestAddress
from .types.register_user_request_licenses_item import RegisterUserRequestLicensesItem
from .types.register_user_request_profile_details import RegisterUserRequestProfileDetails
from .types.register_user_request_role import RegisterUserRequestRole
from .types.register_user_request_roles_item import RegisterUserRequestRolesItem
from .types.update_practice_team_member_request_role import UpdatePracticeTeamMemberRequestRole
from .types.update_practice_team_member_request_roles_item import UpdatePracticeTeamMemberRequestRolesItem
from .types.update_practice_team_member_request_status import UpdatePracticeTeamMemberRequestStatus
from .types.update_practice_team_prescriber_request_address import UpdatePracticeTeamPrescriberRequestAddress
from .types.update_practice_team_prescriber_request_practice_status import (
    UpdatePracticeTeamPrescriberRequestPracticeStatus,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TeamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTeamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTeamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTeamClient
        """
        return self._raw_client

    def register_user(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: RegisterUserRequestRole,
        identity_attestation: bool,
        roles: typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[RegisterUserRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[RegisterUserRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterUserResponse:
        """
        Requires team:write and Idempotency-Key. Registers a practice member without an invitation. Test requires synthetic .test emails and Affinity Test NPIs. Live requires approved integration and practice access. Identity attestation records the integration's assertion; it does not verify login email or clinical credentials. Existing memberships and verified provider records are preserved. Use the returned user ID for orders and signing.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : RegisterUserRequestRole

        identity_attestation : bool

        roles : typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]]

        profile_details : typing.Optional[RegisterUserRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[RegisterUserRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterUserResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.register_user(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
            external_id="externalId",
            email="email",
            name="name",
            role="administrator",
            identity_attestation=True,
        )
        """
        _response = self._raw_client.register_user(
            practice_id,
            idempotency_key=idempotency_key,
            external_id=external_id,
            email=email,
            name=name,
            role=role,
            identity_attestation=identity_attestation,
            roles=roles,
            profile_details=profile_details,
            npi=npi,
            licenses=licenses,
            legal_name=legal_name,
            display_name=display_name,
            credentials=credentials,
            address=address,
            phone=phone,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    def list_practice_team_invitations(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        status: typing.Optional[ListPracticeTeamInvitationsRequestStatus] = None,
        email: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamInvitationsResponse:
        """
        Requires team:read. Lists practice invitations, including invitations sent in Clinic. Filter by pending, expired, accepted, declined, or revoked status, exact email, or your integration externalId. Only your integration and API key mode can see its external identity and onboarding state. Follow person.nextActions after invitation acceptance.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        status : typing.Optional[ListPracticeTeamInvitationsRequestStatus]

        email : typing.Optional[str]

        external_id : typing.Optional[str]
            Match this integration's external identity in the API key's mode.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamInvitationsResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.list_practice_team_invitations(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            starting_after="invite_01j2y8m6jcc9tt24af5pw9x1bc",
            ending_before="invite_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.list_practice_team_invitations(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            status=status,
            email=email,
            external_id=external_id,
            request_options=request_options,
        )
        return _response.data

    def invite_practice_team_person(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: typing.Optional[InvitePracticeTeamPersonRequestRole] = OMIT,
        roles: typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[InvitePracticeTeamPersonRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[InvitePracticeTeamPersonRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvitePracticeTeamPersonResponse:
        """
        Requires team:write on the practice key or its platform key. Use roles to combine administrator, prescriber, clinical_staff, billing, or developer presets. Ownership uses the protected owner designation. The singular role field remains available for single-role assignments. Creates a real organization invitation and optional prescriber setup. The recipient must accept with their Affinity account. Repeating the same external identity retries pending invitation delivery. Accepted invitations do not change existing access. Team membership is shared between Test and Live; the external identity is mode-scoped. Keys cannot accept invitations. Headless registration and signing use separate endpoints.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : typing.Optional[InvitePracticeTeamPersonRequestRole]

        roles : typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestRolesItem]]

        profile_details : typing.Optional[InvitePracticeTeamPersonRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[InvitePracticeTeamPersonRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvitePracticeTeamPersonResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.invite_practice_team_person(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
            external_id="externalId",
            email="email",
            name="name",
        )
        """
        _response = self._raw_client.invite_practice_team_person(
            practice_id,
            idempotency_key=idempotency_key,
            external_id=external_id,
            email=email,
            name=name,
            role=role,
            roles=roles,
            profile_details=profile_details,
            npi=npi,
            licenses=licenses,
            legal_name=legal_name,
            display_name=display_name,
            credentials=credentials,
            address=address,
            phone=phone,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    def get_practice_team(
        self, practice_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamResponse:
        """
        Requires team:read. Returns counts of members, invitations, and prescribers. Use the paginated members, prescribers, and invitations collections for individual records. Team access and clinician credentials are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.get_practice_team(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get_practice_team(practice_id, request_options=request_options)
        return _response.data

    def list_practice_team_members(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        role: typing.Optional[ListPracticeTeamMembersRequestRole] = None,
        status: typing.Optional[ListPracticeTeamMembersRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamMembersResponse:
        """
        Requires team:read. Search the roster by name or email, and filter by role or membership status. Includes members invited in Clinic, location access, and account-specific prescriber connections. Memberships are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        search : typing.Optional[str]

        role : typing.Optional[ListPracticeTeamMembersRequestRole]

        status : typing.Optional[ListPracticeTeamMembersRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamMembersResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.list_practice_team_members(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            starting_after="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
            ending_before="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.list_practice_team_members(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            role=role,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def list_practice_team_prescribers(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        npi: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        status: typing.Optional[ListPracticeTeamPrescribersRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamPrescribersResponse:
        """
        Requires team:read. Filter practice prescribers by name, NPI, state, and practice status. Records include submitted licenses and their IDs. Signing authority also requires an active account connection, Live practice access, and prescription eligibility.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        search : typing.Optional[str]

        npi : typing.Optional[str]

        state : typing.Optional[str]
            Match a submitted license jurisdiction. This does not establish signing eligibility.

        status : typing.Optional[ListPracticeTeamPrescribersRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamPrescribersResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.list_practice_team_prescribers(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            starting_after="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            ending_before="prov_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.list_practice_team_prescribers(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            npi=npi,
            state=state,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def get_practice_team_member(
        self, practice_id: str, member_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamMemberResponse:
        """
        Requires team:read. Returns current account membership, roles, location access, and prescriber connection. The member ID identifies practice access; it is not the integration user ID used by orders.

        Parameters
        ----------
        practice_id : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamMemberResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.get_practice_team_member(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            member_id="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get_practice_team_member(practice_id, member_id, request_options=request_options)
        return _response.data

    def update_practice_team_member(
        self,
        practice_id: str,
        member_id: str,
        *,
        idempotency_key: str,
        role: typing.Optional[UpdatePracticeTeamMemberRequestRole] = OMIT,
        roles: typing.Optional[typing.Sequence[UpdatePracticeTeamMemberRequestRolesItem]] = OMIT,
        status: typing.Optional[UpdatePracticeTeamMemberRequestStatus] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamMemberResponse:
        """
        Requires team:write. Supply role, status, or locationIds; omitted values stay unchanged. A role replaces existing roles. Disable access with status disabled. An empty locationIds array grants all practice locations. Ownership changes require an active practice owner using a personal API key; service keys manage non-owner memberships. The final active owner cannot be removed. Changes apply to both Test and Live. Sign-in email and account security remain account settings.

        Parameters
        ----------
        practice_id : str

        member_id : str

        idempotency_key : str

        role : typing.Optional[UpdatePracticeTeamMemberRequestRole]

        roles : typing.Optional[typing.Sequence[UpdatePracticeTeamMemberRequestRolesItem]]

        status : typing.Optional[UpdatePracticeTeamMemberRequestStatus]

        location_ids : typing.Optional[typing.Sequence[str]]
            Replace location access. An empty array grants access to all practice locations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamMemberResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.update_practice_team_member(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            member_id="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
        )
        """
        _response = self._raw_client.update_practice_team_member(
            practice_id,
            member_id,
            idempotency_key=idempotency_key,
            role=role,
            roles=roles,
            status=status,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    def get_practice_team_prescriber(
        self, practice_id: str, prescriber_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamPrescriberResponse:
        """
        Requires team:read. Returns the clinical profile and submitted licenses, including license IDs. This is setup information, not a signing authorization.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamPrescriberResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.get_practice_team_prescriber(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get_practice_team_prescriber(
            practice_id, prescriber_id, request_options=request_options
        )
        return _response.data

    def update_practice_team_prescriber(
        self,
        practice_id: str,
        prescriber_id: str,
        *,
        idempotency_key: str,
        display_name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[UpdatePracticeTeamPrescriberRequestAddress] = OMIT,
        practice_status: typing.Optional[UpdatePracticeTeamPrescriberRequestPracticeStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamPrescriberResponse:
        """
        Requires team:write. Set practiceStatus to inactive to remove prescribing access in this practice, or active to restore an existing association. This does not create membership or signing authority. Practice status applies to Test and Live. Shared identity and license edits require Affinity support.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        idempotency_key : str

        display_name : typing.Optional[str]

        legal_name : typing.Optional[str]

        credentials : typing.Optional[str]

        phone : typing.Optional[str]

        address : typing.Optional[UpdatePracticeTeamPrescriberRequestAddress]

        practice_status : typing.Optional[UpdatePracticeTeamPrescriberRequestPracticeStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamPrescriberResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.update_practice_team_prescriber(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
        )
        """
        _response = self._raw_client.update_practice_team_prescriber(
            practice_id,
            prescriber_id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            legal_name=legal_name,
            credentials=credentials,
            phone=phone,
            address=address,
            practice_status=practice_status,
            request_options=request_options,
        )
        return _response.data

    def create_practice_team_license(
        self,
        practice_id: str,
        prescriber_id: str,
        *,
        idempotency_key: str,
        state: str,
        license_number: str,
        expires_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePracticeTeamLicenseResponse:
        """
        Requires team:write and an active accepted prescriber account connection in this practice. Adds a license. Expiration is optional, but must be in the future when supplied. An exact repeat returns the existing license; update an existing license with PATCH and its license ID. Licenses are shared across practices and Test/Live. Other licenses stay unchanged.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        idempotency_key : str

        state : str

        license_number : str

        expires_at : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePracticeTeamLicenseResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.create_practice_team_license(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
            state="state",
            license_number="licenseNumber",
        )
        """
        _response = self._raw_client.create_practice_team_license(
            practice_id,
            prescriber_id,
            idempotency_key=idempotency_key,
            state=state,
            license_number=license_number,
            expires_at=expires_at,
            request_options=request_options,
        )
        return _response.data

    def update_practice_team_license(
        self,
        practice_id: str,
        prescriber_id: str,
        license_id: str,
        *,
        idempotency_key: str,
        state: typing.Optional[str] = OMIT,
        license_number: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamLicenseResponse:
        """
        Requires team:write and an active accepted prescriber account connection in this practice. Correct the state or license number, or set or clear the optional expiresAt value. A supplied expiration must be in the future. Other licenses stay unchanged. Changes apply across practices and Test/Live.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        license_id : str

        idempotency_key : str

        state : typing.Optional[str]

        license_number : typing.Optional[str]

        expires_at : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamLicenseResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.update_practice_team_license(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            license_id="lic_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
        )
        """
        _response = self._raw_client.update_practice_team_license(
            practice_id,
            prescriber_id,
            license_id,
            idempotency_key=idempotency_key,
            state=state,
            license_number=license_number,
            expires_at=expires_at,
            request_options=request_options,
        )
        return _response.data

    def get_practice_team_invitation(
        self, practice_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamInvitationResponse:
        """
        Requires team:read. Returns invitation status and current onboarding state for your integration. An accepted invitation can still have disabled membership or pending clinical review. Invitation tokens are never returned.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.get_practice_team_invitation(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get_practice_team_invitation(
            practice_id, invitation_id, request_options=request_options
        )
        return _response.data

    def revoke_practice_team_invitation(
        self,
        practice_id: str,
        invitation_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RevokePracticeTeamInvitationResponse:
        """
        Requires team:write. Revokes a pending or expired invitation and its pending prescriber account connection. Repeating the revoke returns the revoked invitation. Accepted invitations return 409; disable the member instead. Retains invitation history.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevokePracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.revoke_practice_team_invitation(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
        )
        """
        _response = self._raw_client.revoke_practice_team_invitation(
            practice_id, invitation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def resend_practice_team_invitation(
        self,
        practice_id: str,
        invitation_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResendPracticeTeamInvitationResponse:
        """
        Requires team:write. Resends a pending or expired invitation with the same ID, recipient, roles, and locations. The previous link stops working and the new link expires in seven days. Accepted and revoked invitations return 409. A 502 means the invitation was saved but email delivery could not be confirmed; retry this operation.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResendPracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.team.resend_practice_team_invitation(
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
            idempotency_key="Idempotency-Key",
        )
        """
        _response = self._raw_client.resend_practice_team_invitation(
            practice_id, invitation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncTeamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTeamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTeamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTeamClient
        """
        return self._raw_client

    async def register_user(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: RegisterUserRequestRole,
        identity_attestation: bool,
        roles: typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[RegisterUserRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[RegisterUserRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterUserResponse:
        """
        Requires team:write and Idempotency-Key. Registers a practice member without an invitation. Test requires synthetic .test emails and Affinity Test NPIs. Live requires approved integration and practice access. Identity attestation records the integration's assertion; it does not verify login email or clinical credentials. Existing memberships and verified provider records are preserved. Use the returned user ID for orders and signing.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : RegisterUserRequestRole

        identity_attestation : bool

        roles : typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]]

        profile_details : typing.Optional[RegisterUserRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[RegisterUserRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterUserResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.register_user(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
                external_id="externalId",
                email="email",
                name="name",
                role="administrator",
                identity_attestation=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_user(
            practice_id,
            idempotency_key=idempotency_key,
            external_id=external_id,
            email=email,
            name=name,
            role=role,
            identity_attestation=identity_attestation,
            roles=roles,
            profile_details=profile_details,
            npi=npi,
            licenses=licenses,
            legal_name=legal_name,
            display_name=display_name,
            credentials=credentials,
            address=address,
            phone=phone,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    async def list_practice_team_invitations(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        status: typing.Optional[ListPracticeTeamInvitationsRequestStatus] = None,
        email: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamInvitationsResponse:
        """
        Requires team:read. Lists practice invitations, including invitations sent in Clinic. Filter by pending, expired, accepted, declined, or revoked status, exact email, or your integration externalId. Only your integration and API key mode can see its external identity and onboarding state. Follow person.nextActions after invitation acceptance.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        status : typing.Optional[ListPracticeTeamInvitationsRequestStatus]

        email : typing.Optional[str]

        external_id : typing.Optional[str]
            Match this integration's external identity in the API key's mode.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamInvitationsResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.list_practice_team_invitations(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                starting_after="invite_01j2y8m6jcc9tt24af5pw9x1bc",
                ending_before="invite_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_practice_team_invitations(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            status=status,
            email=email,
            external_id=external_id,
            request_options=request_options,
        )
        return _response.data

    async def invite_practice_team_person(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: typing.Optional[InvitePracticeTeamPersonRequestRole] = OMIT,
        roles: typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[InvitePracticeTeamPersonRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[InvitePracticeTeamPersonRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvitePracticeTeamPersonResponse:
        """
        Requires team:write on the practice key or its platform key. Use roles to combine administrator, prescriber, clinical_staff, billing, or developer presets. Ownership uses the protected owner designation. The singular role field remains available for single-role assignments. Creates a real organization invitation and optional prescriber setup. The recipient must accept with their Affinity account. Repeating the same external identity retries pending invitation delivery. Accepted invitations do not change existing access. Team membership is shared between Test and Live; the external identity is mode-scoped. Keys cannot accept invitations. Headless registration and signing use separate endpoints.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : typing.Optional[InvitePracticeTeamPersonRequestRole]

        roles : typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestRolesItem]]

        profile_details : typing.Optional[InvitePracticeTeamPersonRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[InvitePracticeTeamPersonRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[InvitePracticeTeamPersonRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvitePracticeTeamPersonResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.invite_practice_team_person(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
                external_id="externalId",
                email="email",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invite_practice_team_person(
            practice_id,
            idempotency_key=idempotency_key,
            external_id=external_id,
            email=email,
            name=name,
            role=role,
            roles=roles,
            profile_details=profile_details,
            npi=npi,
            licenses=licenses,
            legal_name=legal_name,
            display_name=display_name,
            credentials=credentials,
            address=address,
            phone=phone,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    async def get_practice_team(
        self, practice_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamResponse:
        """
        Requires team:read. Returns counts of members, invitations, and prescribers. Use the paginated members, prescribers, and invitations collections for individual records. Team access and clinician credentials are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.get_practice_team(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_practice_team(practice_id, request_options=request_options)
        return _response.data

    async def list_practice_team_members(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        role: typing.Optional[ListPracticeTeamMembersRequestRole] = None,
        status: typing.Optional[ListPracticeTeamMembersRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamMembersResponse:
        """
        Requires team:read. Search the roster by name or email, and filter by role or membership status. Includes members invited in Clinic, location access, and account-specific prescriber connections. Memberships are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        search : typing.Optional[str]

        role : typing.Optional[ListPracticeTeamMembersRequestRole]

        status : typing.Optional[ListPracticeTeamMembersRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamMembersResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.list_practice_team_members(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                starting_after="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
                ending_before="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_practice_team_members(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            role=role,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def list_practice_team_prescribers(
        self,
        practice_id: str,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        npi: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        status: typing.Optional[ListPracticeTeamPrescribersRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPracticeTeamPrescribersResponse:
        """
        Requires team:read. Filter practice prescribers by name, NPI, state, and practice status. Records include submitted licenses and their IDs. Signing authority also requires an active account connection, Live practice access, and prescription eligibility.

        Parameters
        ----------
        practice_id : str

        limit : typing.Optional[int]

        starting_after : typing.Optional[str]

        ending_before : typing.Optional[str]

        search : typing.Optional[str]

        npi : typing.Optional[str]

        state : typing.Optional[str]
            Match a submitted license jurisdiction. This does not establish signing eligibility.

        status : typing.Optional[ListPracticeTeamPrescribersRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPracticeTeamPrescribersResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.list_practice_team_prescribers(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                starting_after="prov_01j2y8m6jcc9tt24af5pw9x1bc",
                ending_before="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_practice_team_prescribers(
            practice_id,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            npi=npi,
            state=state,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def get_practice_team_member(
        self, practice_id: str, member_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamMemberResponse:
        """
        Requires team:read. Returns current account membership, roles, location access, and prescriber connection. The member ID identifies practice access; it is not the integration user ID used by orders.

        Parameters
        ----------
        practice_id : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamMemberResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.get_practice_team_member(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                member_id="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_practice_team_member(
            practice_id, member_id, request_options=request_options
        )
        return _response.data

    async def update_practice_team_member(
        self,
        practice_id: str,
        member_id: str,
        *,
        idempotency_key: str,
        role: typing.Optional[UpdatePracticeTeamMemberRequestRole] = OMIT,
        roles: typing.Optional[typing.Sequence[UpdatePracticeTeamMemberRequestRolesItem]] = OMIT,
        status: typing.Optional[UpdatePracticeTeamMemberRequestStatus] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamMemberResponse:
        """
        Requires team:write. Supply role, status, or locationIds; omitted values stay unchanged. A role replaces existing roles. Disable access with status disabled. An empty locationIds array grants all practice locations. Ownership changes require an active practice owner using a personal API key; service keys manage non-owner memberships. The final active owner cannot be removed. Changes apply to both Test and Live. Sign-in email and account security remain account settings.

        Parameters
        ----------
        practice_id : str

        member_id : str

        idempotency_key : str

        role : typing.Optional[UpdatePracticeTeamMemberRequestRole]

        roles : typing.Optional[typing.Sequence[UpdatePracticeTeamMemberRequestRolesItem]]

        status : typing.Optional[UpdatePracticeTeamMemberRequestStatus]

        location_ids : typing.Optional[typing.Sequence[str]]
            Replace location access. An empty array grants access to all practice locations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamMemberResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.update_practice_team_member(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                member_id="mbr_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_practice_team_member(
            practice_id,
            member_id,
            idempotency_key=idempotency_key,
            role=role,
            roles=roles,
            status=status,
            location_ids=location_ids,
            request_options=request_options,
        )
        return _response.data

    async def get_practice_team_prescriber(
        self, practice_id: str, prescriber_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamPrescriberResponse:
        """
        Requires team:read. Returns the clinical profile and submitted licenses, including license IDs. This is setup information, not a signing authorization.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamPrescriberResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.get_practice_team_prescriber(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_practice_team_prescriber(
            practice_id, prescriber_id, request_options=request_options
        )
        return _response.data

    async def update_practice_team_prescriber(
        self,
        practice_id: str,
        prescriber_id: str,
        *,
        idempotency_key: str,
        display_name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        address: typing.Optional[UpdatePracticeTeamPrescriberRequestAddress] = OMIT,
        practice_status: typing.Optional[UpdatePracticeTeamPrescriberRequestPracticeStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamPrescriberResponse:
        """
        Requires team:write. Set practiceStatus to inactive to remove prescribing access in this practice, or active to restore an existing association. This does not create membership or signing authority. Practice status applies to Test and Live. Shared identity and license edits require Affinity support.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        idempotency_key : str

        display_name : typing.Optional[str]

        legal_name : typing.Optional[str]

        credentials : typing.Optional[str]

        phone : typing.Optional[str]

        address : typing.Optional[UpdatePracticeTeamPrescriberRequestAddress]

        practice_status : typing.Optional[UpdatePracticeTeamPrescriberRequestPracticeStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamPrescriberResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.update_practice_team_prescriber(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_practice_team_prescriber(
            practice_id,
            prescriber_id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            legal_name=legal_name,
            credentials=credentials,
            phone=phone,
            address=address,
            practice_status=practice_status,
            request_options=request_options,
        )
        return _response.data

    async def create_practice_team_license(
        self,
        practice_id: str,
        prescriber_id: str,
        *,
        idempotency_key: str,
        state: str,
        license_number: str,
        expires_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePracticeTeamLicenseResponse:
        """
        Requires team:write and an active accepted prescriber account connection in this practice. Adds a license. Expiration is optional, but must be in the future when supplied. An exact repeat returns the existing license; update an existing license with PATCH and its license ID. Licenses are shared across practices and Test/Live. Other licenses stay unchanged.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        idempotency_key : str

        state : str

        license_number : str

        expires_at : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePracticeTeamLicenseResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.create_practice_team_license(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
                state="state",
                license_number="licenseNumber",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_practice_team_license(
            practice_id,
            prescriber_id,
            idempotency_key=idempotency_key,
            state=state,
            license_number=license_number,
            expires_at=expires_at,
            request_options=request_options,
        )
        return _response.data

    async def update_practice_team_license(
        self,
        practice_id: str,
        prescriber_id: str,
        license_id: str,
        *,
        idempotency_key: str,
        state: typing.Optional[str] = OMIT,
        license_number: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePracticeTeamLicenseResponse:
        """
        Requires team:write and an active accepted prescriber account connection in this practice. Correct the state or license number, or set or clear the optional expiresAt value. A supplied expiration must be in the future. Other licenses stay unchanged. Changes apply across practices and Test/Live.

        Parameters
        ----------
        practice_id : str

        prescriber_id : str

        license_id : str

        idempotency_key : str

        state : typing.Optional[str]

        license_number : typing.Optional[str]

        expires_at : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePracticeTeamLicenseResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.update_practice_team_license(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                prescriber_id="prov_01j2y8m6jcc9tt24af5pw9x1bc",
                license_id="lic_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_practice_team_license(
            practice_id,
            prescriber_id,
            license_id,
            idempotency_key=idempotency_key,
            state=state,
            license_number=license_number,
            expires_at=expires_at,
            request_options=request_options,
        )
        return _response.data

    async def get_practice_team_invitation(
        self, practice_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPracticeTeamInvitationResponse:
        """
        Requires team:read. Returns invitation status and current onboarding state for your integration. An accepted invitation can still have disabled membership or pending clinical review. Invitation tokens are never returned.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.get_practice_team_invitation(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_practice_team_invitation(
            practice_id, invitation_id, request_options=request_options
        )
        return _response.data

    async def revoke_practice_team_invitation(
        self,
        practice_id: str,
        invitation_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RevokePracticeTeamInvitationResponse:
        """
        Requires team:write. Revokes a pending or expired invitation and its pending prescriber account connection. Repeating the revoke returns the revoked invitation. Accepted invitations return 409; disable the member instead. Retains invitation history.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevokePracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.revoke_practice_team_invitation(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_practice_team_invitation(
            practice_id, invitation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def resend_practice_team_invitation(
        self,
        practice_id: str,
        invitation_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResendPracticeTeamInvitationResponse:
        """
        Requires team:write. Resends a pending or expired invitation with the same ID, recipient, roles, and locations. The previous link stops working and the new link expires in seven days. Accepted and revoked invitations return 409. A 502 means the invitation was saved but email delivery could not be confirmed; retry this operation.

        Parameters
        ----------
        practice_id : str

        invitation_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResendPracticeTeamInvitationResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.team.resend_practice_team_invitation(
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
                invitation_id="invite_01j2y8m6jcc9tt24af5pw9x1bc",
                idempotency_key="Idempotency-Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resend_practice_team_invitation(
            practice_id, invitation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
