# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.get_practice_team_response import GetPracticeTeamResponse
from ..types.problem import Problem
from ..types.register_user_response import RegisterUserResponse
from .types.register_user_request_address import RegisterUserRequestAddress
from .types.register_user_request_licenses_item import RegisterUserRequestLicensesItem
from .types.register_user_request_profile_details import RegisterUserRequestProfileDetails
from .types.register_user_request_role import RegisterUserRequestRole
from .types.register_user_request_roles_item import RegisterUserRequestRolesItem
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTeamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def register(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: RegisterUserRequestRole,
        identity_attestation: bool,
        roles: typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[RegisterUserRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[RegisterUserRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RegisterUserResponse]:
        """
        Requires team:write and Idempotency-Key. Registers a practice member without an invitation. Test requires synthetic .test emails and Affinity Test NPIs. Live requires approved integration and practice access. Identity attestation records the integration's assertion; it does not verify login email or clinical credentials. Existing memberships and verified provider records are preserved. Use the returned user ID for orders and signing.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : RegisterUserRequestRole

        identity_attestation : bool

        roles : typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]]

        profile_details : typing.Optional[RegisterUserRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[RegisterUserRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RegisterUserResponse]
            HTTP 200
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/practices/{encode_path_param(practice_id)}/users",
            method="POST",
            json={
                "externalId": external_id,
                "email": email,
                "name": name,
                "role": role,
                "roles": roles,
                "profileDetails": convert_and_respect_annotation_metadata(
                    object_=profile_details,
                    annotation=typing.Optional[RegisterUserRequestProfileDetails],
                    direction="write",
                ),
                "npi": npi,
                "licenses": convert_and_respect_annotation_metadata(
                    object_=licenses,
                    annotation=typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]],
                    direction="write",
                ),
                "legalName": legal_name,
                "displayName": display_name,
                "credentials": credentials,
                "address": convert_and_respect_annotation_metadata(
                    object_=address, annotation=typing.Optional[RegisterUserRequestAddress], direction="write"
                ),
                "phone": phone,
                "locationIds": location_ids,
                "identityAttestation": identity_attestation,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RegisterUserResponse,
                    parse_obj_as(
                        type_=RegisterUserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, practice_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetPracticeTeamResponse]:
        """
        Requires team:read. Returns counts of members, invitations, and prescribers. Use the paginated members, prescribers, and invitations collections for individual records. Team access and clinician credentials are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetPracticeTeamResponse]
            HTTP 200
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/practices/{encode_path_param(practice_id)}/team",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPracticeTeamResponse,
                    parse_obj_as(
                        type_=GetPracticeTeamResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTeamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def register(
        self,
        practice_id: str,
        *,
        idempotency_key: str,
        external_id: str,
        email: str,
        name: str,
        role: RegisterUserRequestRole,
        identity_attestation: bool,
        roles: typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]] = OMIT,
        profile_details: typing.Optional[RegisterUserRequestProfileDetails] = OMIT,
        npi: typing.Optional[str] = OMIT,
        licenses: typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        credentials: typing.Optional[str] = OMIT,
        address: typing.Optional[RegisterUserRequestAddress] = OMIT,
        phone: typing.Optional[str] = OMIT,
        location_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RegisterUserResponse]:
        """
        Requires team:write and Idempotency-Key. Registers a practice member without an invitation. Test requires synthetic .test emails and Affinity Test NPIs. Live requires approved integration and practice access. Identity attestation records the integration's assertion; it does not verify login email or clinical credentials. Existing memberships and verified provider records are preserved. Use the returned user ID for orders and signing.

        Parameters
        ----------
        practice_id : str

        idempotency_key : str

        external_id : str

        email : str

        name : str

        role : RegisterUserRequestRole

        identity_attestation : bool

        roles : typing.Optional[typing.Sequence[RegisterUserRequestRolesItem]]

        profile_details : typing.Optional[RegisterUserRequestProfileDetails]

        npi : typing.Optional[str]

        licenses : typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]]

        legal_name : typing.Optional[str]

        display_name : typing.Optional[str]

        credentials : typing.Optional[str]

        address : typing.Optional[RegisterUserRequestAddress]

        phone : typing.Optional[str]

        location_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RegisterUserResponse]
            HTTP 200
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/practices/{encode_path_param(practice_id)}/users",
            method="POST",
            json={
                "externalId": external_id,
                "email": email,
                "name": name,
                "role": role,
                "roles": roles,
                "profileDetails": convert_and_respect_annotation_metadata(
                    object_=profile_details,
                    annotation=typing.Optional[RegisterUserRequestProfileDetails],
                    direction="write",
                ),
                "npi": npi,
                "licenses": convert_and_respect_annotation_metadata(
                    object_=licenses,
                    annotation=typing.Optional[typing.Sequence[RegisterUserRequestLicensesItem]],
                    direction="write",
                ),
                "legalName": legal_name,
                "displayName": display_name,
                "credentials": credentials,
                "address": convert_and_respect_annotation_metadata(
                    object_=address, annotation=typing.Optional[RegisterUserRequestAddress], direction="write"
                ),
                "phone": phone,
                "locationIds": location_ids,
                "identityAttestation": identity_attestation,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RegisterUserResponse,
                    parse_obj_as(
                        type_=RegisterUserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, practice_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetPracticeTeamResponse]:
        """
        Requires team:read. Returns counts of members, invitations, and prescribers. Use the paginated members, prescribers, and invitations collections for individual records. Team access and clinician credentials are shared between Test and Live.

        Parameters
        ----------
        practice_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetPracticeTeamResponse]
            HTTP 200
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/practices/{encode_path_param(practice_id)}/team",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPracticeTeamResponse,
                    parse_obj_as(
                        type_=GetPracticeTeamResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Problem,
                        parse_obj_as(
                            type_=Problem,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
