# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.platform_public_api_selling_prices_read_selling_price_response import (
    PlatformPublicApiSellingPricesReadSellingPriceResponse,
)
from .raw_client import AsyncRawSellingPricesClient, RawSellingPricesClient


class SellingPricesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSellingPricesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSellingPricesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSellingPricesClient
        """
        return self._raw_client

    def get(
        self,
        catalog_item_id: str,
        *,
        practice_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlatformPublicApiSellingPricesReadSellingPriceResponse:
        """
        Requires selling_prices:read. Reads the Affinity-managed purchase-price override inherited by this platform's practices unless Affinity sets a practice override. Use the practice-scoped catalog for effective practice prices and presentation-price when an Affinity default may be absent. Platforms cannot edit purchase prices.

        Parameters
        ----------
        catalog_item_id : str

        practice_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformPublicApiSellingPricesReadSellingPriceResponse
            HTTP 200

        Examples
        --------
        from affinity import Affinity

        client = Affinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.catalog.selling_prices.get(
            catalog_item_id="cat_01j2y8m6jcc9tt24af5pw9x1bc",
            practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
        )
        """
        _response = self._raw_client.get(catalog_item_id, practice_id=practice_id, request_options=request_options)
        return _response.data


class AsyncSellingPricesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSellingPricesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSellingPricesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSellingPricesClient
        """
        return self._raw_client

    async def get(
        self,
        catalog_item_id: str,
        *,
        practice_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlatformPublicApiSellingPricesReadSellingPriceResponse:
        """
        Requires selling_prices:read. Reads the Affinity-managed purchase-price override inherited by this platform's practices unless Affinity sets a practice override. Use the practice-scoped catalog for effective practice prices and presentation-price when an Affinity default may be absent. Platforms cannot edit purchase prices.

        Parameters
        ----------
        catalog_item_id : str

        practice_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformPublicApiSellingPricesReadSellingPriceResponse
            HTTP 200

        Examples
        --------
        import asyncio

        from affinity import AsyncAffinity

        client = AsyncAffinity(
            affinity_version="YOUR_AFFINITY_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.catalog.selling_prices.get(
                catalog_item_id="cat_01j2y8m6jcc9tt24af5pw9x1bc",
                practice_id="prac_01j2y8m6jcc9tt24af5pw9x1bc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            catalog_item_id, practice_id=practice_id, request_options=request_options
        )
        return _response.data
